#!/usr/bin/env python3
"""V-CTN-017 (L0): the controller mints no RBAC -- parsed, not read.

09 §6's catalog line is half check and half instruction: *"The controller mints no RBAC -- parse its
ClusterRole, do not inspect it by eye"*. 08 §7 says the same thing in the same words -- *"assert by
parsing the generated RBAC, not by inspection"*. Both are worth taking literally. `manager-role` is
a hundred and forty lines of indented lists in which one extra four-character resource name reads
exactly like the eleven around it, and the reviewer who approves it has already read four other
files. The property is not that the ClusterRole looks narrow. It is that no rule anywhere in the
control plane's install tree confers the ability to create, modify, bind, or impersonate an RBAC
object -- and that is a parse.

WHY THIS IS THE FIRST DOMINO. Every scope ceiling in this system is a grant the pipeline applied
ahead of time. The reader SA can write nothing; the actor SA can write only its tier's template
inside its scope; both are pre-created, GitOps-managed manifests the controller only ever references
by name (08 §2.7, "it consumes identity; it never produces it"). If the controller could mint a Role
and a RoleBinding, it could grant an agent whatever it liked at runtime and no static check of the
rendered templates would ever see it -- the templates would still be correct, and the authority
would simply not have come from them. `actor-grant-single-sourced.py` would stay green while the
thing it single-sources stopped being the only source. "An agent cannot widen its own authority"
would then hold exactly as long as the controller is neither buggy nor compromised, which is the
assumption 08 §4 explicitly refuses to make.

TWO ARTIFACTS, AND THEIR AGREEMENT IS A PROPERTY OF ITS OWN. `config/rbac/role.yaml` is generated by
controller-gen from the `+kubebuilder:rbac` comments under `k8s-operator/`. The rendered file is what
`kustomize build` installs; the markers are what a developer edits. Asserting over one of them leaves
a hole, and a different hole each way. Over the rendered file alone: a marker added without running
`make manifests` is invisible until CI regenerates, so the grant lands in a commit that touches no
YAML and appears in a later one that touches nothing else. Over the markers alone: a hand-edited
`role.yaml` is invisible, and that is the file that ships. So properties 2 through 6 run over BOTH,
and property 7 asserts the two agree triple for triple -- which catches the stale render on its own,
one commit before the marker becomes real.

READ VERBS ON RBAC ARE NOT PERMITTED, AND THAT IS THE SPEC'S CALL RATHER THAN THIS CHECK'S. 08 §7:
*"Its `ClusterRole` contains no verb on `roles`/`clusterroles`/`rolebindings`/`clusterrolebindings`/
`serviceaccounts` beyond `get;list;watch` on ServiceAccounts"*. The "beyond" clause attaches to
ServiceAccounts alone; the four RBAC kinds get zero verbs, reads included. It is worth being honest
that `get roles` is not by itself an escalation -- it reads authority, it does not confer it -- so
the line is drawn at zero for two reasons better than "reads are scary". First, the controller has
no use for it: no shipped Go file under `k8s-operator/` so much as imports `k8s.io/api/rbac/v1`
(property 9), so a read verb on a Role could only ever be a dead grant, and a dead grant on the
RBAC API group is the one nobody re-reads when it stops being dead. Second, zero is the only bound a
parser can hold without a judgement call: "reads are fine, writes are not" requires the check to
decide which verbs are reads, and 09 §11.4 records what that costs -- a write-verb deny-list once
admitted `impersonate`, which is cluster-admin spelled differently. An empty allow-list has no edge
to get wrong.

A SERVICEACCOUNT IS AN IDENTITY; A ROLEBINDING IS A GRANT. The controller must READ ServiceAccounts.
It stamps `spec.serviceAccountName` onto the two Deployments it renders, and it has to be able to
tell an absent SA from a present one so it can fail closed rather than launch a pod under `default`.
It may not create or modify one: 08 §2.7's "May not" list names ServiceAccount alongside the four
RBAC kinds. An SA on its own confers nothing -- it is a name until a RoleBinding mentions it -- but
the two halves of minting authority are the identity and the grant, and a controller holding one
half is one bug away from the other. `serviceaccounts/token` is not the same question: `create` on
it is the TokenRequest API and it returns a bearer credential for that SA, which is the credential
itself rather than a reference to it. Hence property 3's shape -- the base resource may be read, and
no subresource of it may be touched at all.

WHAT COUNTS AS RBAC-MINTING, ARGUED. `rbac.authorization.k8s.io` is the obvious group and it is not
the whole answer, because none of the three verbs that matter most is a write:

  * `escalate` on `roles`/`clusterroles` lifts the API server's own escalation-prevention check --
    the one thing that stops a holder of `create roles` from writing a Role wider than its own.
  * `bind` grants any Role the holder can name, without needing `escalate` and without needing to
    hold the permissions being bound.
  * `impersonate` on `serviceaccounts`/`users`/`groups` is every identity in the cluster at once. It
    appears on core resources, not on RBAC ones, so a check keyed to the RBAC API group misses it
    entirely.

That is why the verb constraint here is an ALLOW-LIST (09 §11.4, [[LSN-004]]): anything outside
`get/list/watch/create/update/patch/delete/deletecollection` is a finding whether or not anyone
remembered to name it. Properties 4 and 6 exist to attribute the three worst cases by name; property
5 is the bound underneath them, and the three partitions are disjoint so each one is reachable
alone. `certificatesigningrequests/approval` is in scope for the same argument one step out: an
approved CSR is a client certificate, a client certificate carrying `O=system:masters` is
cluster-admin, and the mint is the approval subresource rather than the read.

NINE PROPERTIES.

  1. NON-VACUITY, IN FOUR PARTS. The RBAC corpus parsed to at least three `Role`/`ClusterRole`
     documents and fifteen rules; the generated `manager-role` is among them BY NAME; at least
     twenty `+kubebuilder:rbac` markers were read out of the Go source; and the rule scanner, shown
     a probe document that is nothing but violations, produces every signal it is supposed to.
     Everything below is a scan, and a scan over nothing is the greenest thing in this repo. The
     fourth part is the one that matters most: if the scanner stops recognising an RBAC rule -- a
     renamed field, a parser that returns `None` where it used to return a list -- properties 2
     through 6 go quiet and print a pass ([[LSN-035]], [[LSN-038]]). A role carrying an
     `aggregationRule` also fails here rather than passing: its rules are filled in at runtime by
     the controller-manager, so an empty `rules:` would parse as "grants nothing" and be wrong.
  2. NO VERB ON ANY RBAC RESOURCE. Not `create`, not `bind`, not `get`. Enforced both by API group
     and by resource name, because the group is what the API server matches on and the resource name
     is what survives someone writing the group as `rbac.authorization.k8s.io/v1`.
  3. IDENTITY RESOURCES ARE READ-ONLY, AND THEIR SUBRESOURCES ARE UNTOUCHABLE. `serviceaccounts` and
     `certificatesigningrequests` may carry only `get`/`list`/`watch`; `serviceaccounts/token` and
     `certificatesigningrequests/approval` may carry nothing.
  4. NO WILDCARD, IN ANY OF THE THREE POSITIONS, EACH ITS OWN FINDING. `apiGroups: ["*"]` silently
     includes `rbac.authorization.k8s.io`, so property 2's group scan would find nothing to report
     on a rule that grants everything. `resources: ["*"]` and `verbs: ["*"]` are the same hole one
     column over.
  5. EVERY VERB COMES FROM THE ALLOW-LIST. The bound. `use`, `approve`, `sign`, `attest`, and
     whatever the next API group adds are findings on arrival.
  6. `escalate`, `bind` AND `impersonate` ARE NAMED. A subset of property 5's complement, split out
     so the message says which of the three it is and why it is worse than a write.
  7. THE MARKERS AND THE GENERATED CLUSTERROLE AGREE, TRIPLE FOR TRIPLE, IN BOTH DIRECTIONS. A
     marker-only triple is a `make manifests` that was not run. A rendered-only triple is a
     hand-edit to a generated file, which either ships un-reviewed or is silently deleted by the
     next regeneration.
  8. NO BINDING REACHES A ROLE THIS CHECK DID NOT PARSE. `roleRef: {kind: ClusterRole, name:
     cluster-admin}` hands the controller everything while every property above stays green, because
     there is no rule in the tree to read. Every `roleRef` must resolve inside the corpus.
  9. NO SHIPPED GO FILE IMPORTS `k8s.io/api/rbac/v1`. 08 §7's other half -- *"grep + audit-log check
     that no runtime principal created them"* -- is this, statically. Defense in depth rather than
     the bound: properties 2 through 8 are what make the API server refuse.

WHAT THIS DOES NOT ASSERT, deliberately.

  * That the grants it DOES allow are correctly scoped. `create deployments` cluster-wide is a
    conformance failure under 08 §2.7's normative paragraph and it is a different check's property
    (the G-5 pair). This one is about the RBAC group and the escalation verbs only.
  * The live half. A `ClusterRoleBinding` applied out of band, or an aggregation label pulling the
    controller's SA into `cluster-admin`, is invisible to any parse of the repository. That is
    V-CTN-017's L2 arm -- `kubectl auth can-i` as the controller's SA -- and it is a separate unit.
  * A shipped file building an RBAC object through `unstructured.Unstructured` rather than the typed
    API. Property 9 is the import, which is the signal with no false positives; the four files that
    NAME the RBAC kinds as strings (`internal/broker/classify`, `internal/broker/verify`) are
    classifying inbound envelopes by target kind, and a rule that flagged them would be a rule
    against the classifier existing.

WHAT ALREADY EXISTED, AND WHY THIS IS NOT IT. `invariants-gate.py`'s V-CTN-037 holds TEST-ONLY grants
-- documents carrying `kube-agents/test-only-grant` -- to a similar ceiling, and confines them to
`dev/`. `actor-grant-single-sourced.py` (V-BRK-013) single-sources the AGENT identities in
`k8s-operator/scripts/*.yaml.template` and `examples/gitops-repo/` against 06 §2.2 and §2.2.1.
Neither one reads `k8s-operator/config/`, which is where the control plane's own identities live, so
the operator's ClusterRole was asserted by nobody. The corpus here is therefore exactly the RBAC
documents under `k8s-operator/config/` -- discovered by scanning that tree rather than by naming
`role.yaml` ([[LSN-036]]), because `brake_role.yaml` and `config/router/role.yaml` are hand-written,
arrived after the generated one, and are equally the control plane's authority.

Run:  python3 dev/tests/controller-mints-no-rbac.py
      python3 dev/tests/controller-mints-no-rbac.py --negative-control
"""

from __future__ import annotations

import pathlib
import re
import sys
from typing import NamedTuple

sys.path.insert(0, str(pathlib.Path(__file__).resolve().parent))
from gitcorpus import read_repo_files  # noqa: E402
from yamlsubset import CorpusSyntaxError, load_corpus  # noqa: E402

REPO = pathlib.Path(__file__).resolve().parents[2]

# The kustomize tree that installs the control plane. Every Role and ClusterRole under it is an
# identity the operator itself runs as; the agent identities live in `k8s-operator/scripts/` and
# `examples/gitops-repo/` and belong to V-BRK-013.
CONFIG_TREE = "k8s-operator/config"
GO_TREE = "k8s-operator"

# The one controller-gen writes, from `rbac:roleName=manager-role` in the Makefile's `manifests`
# target. Named because property 7 compares it -- and only it -- against the markers.
GENERATED_ROLE = "manager-role"

RBAC_GROUP = "rbac.authorization.k8s.io"
RBAC_RESOURCES = frozenset({"roles", "clusterroles", "rolebindings", "clusterrolebindings"})

# Resources that ARE an identity, or that mint one. The base may be read and never written; no
# subresource of it may be touched at all -- see the docstring on `serviceaccounts/token`.
IDENTITY_RESOURCES = {
    "serviceaccounts": (
        "a ServiceAccount is an identity the pipeline pre-creates and the controller only "
        "references by name (08 §2.7)"
    ),
    "certificatesigningrequests": (
        "an approved CSR is a client certificate, and a client certificate can carry "
        "`O=system:masters`"
    ),
}
READ_VERBS = frozenset({"get", "list", "watch"})

# The ALLOW-LIST (09 §11.4, [[LSN-004]]). Ordinary Kubernetes verbs, and nothing else. This bounds
# the KIND of verb, not the scope of the grant -- whether the controller should hold `delete` on
# Deployments cluster-wide is 08 §2.7's normative paragraph and the G-5 pair's property.
ORDINARY_VERBS = frozenset(
    {"get", "list", "watch", "create", "update", "patch", "delete", "deletecollection"}
)
# A strict subset of everything the allow-list excludes, split out for attribution only.
ESCALATION_VERBS = frozenset({"escalate", "bind", "impersonate"})
WILDCARD = "*"

# Message fragments. Every finding carries exactly one, the probe document in property 1 has to
# provoke all eight, and the negative control's needles are built from them -- so a message reworded
# without reworking the signal fails here rather than going quiet ([[LSN-035]]).
SIG_RBAC = "08 §7 permits the controller no verb at all on RBAC objects"
SIG_IDENTITY = "an identity resource may be read and never written"
SIG_SUBRESOURCE = "that subresource mints a credential"
SIG_WILD_GROUPS = "wildcards its apiGroups"
SIG_WILD_RESOURCES = "wildcards its resources"
SIG_WILD_VERBS = "wildcards its verbs"
SIG_UNLISTED = "that verb is not one of the ordinary Kubernetes verbs"
SIG_ESCALATION = "that verb is not a write and is worse than one"
SIG_MARKER_ONLY = "is declared by a +kubebuilder:rbac marker and absent from the generated ClusterRole"
SIG_RENDER_ONLY = "is in the generated ClusterRole and declared by no +kubebuilder:rbac marker"
SIG_DANGLING_REF = "which no Role or ClusterRole in the control-plane install tree defines"
SIG_GO_IMPORT = "imports k8s.io/api/rbac"

PROBE_SIGNALS = (
    SIG_RBAC,
    SIG_IDENTITY,
    SIG_SUBRESOURCE,
    SIG_WILD_GROUPS,
    SIG_WILD_RESOURCES,
    SIG_WILD_VERBS,
    SIG_UNLISTED,
    SIG_ESCALATION,
)

# A document that is nothing but violations, one per signal. It is an INPUT rather than a constant
# read inside `check` so the negative control can blind it: a row that swaps it for a harmless role
# and still passes would mean the self-test is decoration.
PROBE_ROLE = """apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: probe-every-signal-must-fire
rules:
  - apiGroups:
      - rbac.authorization.k8s.io
    resources:
      - rolebindings
    verbs:
      - create
  - apiGroups:
      - ""
    resources:
      - serviceaccounts
    verbs:
      - create
  - apiGroups:
      - ""
    resources:
      - serviceaccounts/token
    verbs:
      - create
  - apiGroups:
      - "*"
    resources:
      - "*"
    verbs:
      - "*"
  - apiGroups:
      - ""
    resources:
      - pods
    verbs:
      - approve
  - apiGroups:
      - ""
    resources:
      - serviceaccounts
    verbs:
      - impersonate
"""

# Non-vacuity floors, set well under the real corpus (4 roles, 22 rules, 28 markers) so an ordinary
# mutation lands on the property it targets rather than tripping vacuity first.
MIN_ROLES = 3
MIN_RULES = 15
MIN_MARKERS = 20

DOC_SPLIT = re.compile(r"^---[ \t]*$", re.M)
RBAC_KIND = re.compile(
    r"^kind:[ \t]*(Role|ClusterRole|RoleBinding|ClusterRoleBinding)[ \t]*$", re.M
)
MARKER = re.compile(r"^[ \t]*//[ \t]*\+kubebuilder:rbac:(\S+)[ \t]*$")
# `resourceNames` and the fields below are read but not modelled; anything else is a marker shape
# this check does not understand, and it says so rather than dropping it.
KNOWN_MARKER_FIELDS = frozenset({"groups", "resources", "verbs", "resourceNames"})
GO_RBAC_IMPORT = re.compile(r'"k8s\.io/api/rbac/v\w+"')


class Rule(NamedTuple):
    """One RBAC rule, from either artifact. A marker is a rule; that is the whole trick."""

    where: str
    groups: tuple[str, ...]
    resources: tuple[str, ...]
    verbs: tuple[str, ...]

    def triples(self) -> set[tuple[str, str, str]]:
        return {(g, r, v) for g in self.groups for r in self.resources for v in self.verbs}


class Corpus(NamedTuple):
    rules: list[Rule]  # every rule in every Role/ClusterRole under config/
    generated: list[Rule]  # just `manager-role`'s
    defined: set[tuple[str, str]]  # (kind, name) of every role the corpus defines
    bindings: list[tuple[str, str, str]]  # (where, roleRef kind, roleRef name)
    unparsed: list[str]  # documents this check could not read; a finding, never a skip


def _documents(text: str) -> list[tuple[int, str]]:
    return list(enumerate(DOC_SPLIT.split(text)))


def _strings(value) -> tuple[str, ...]:
    """A YAML list of scalars as a tuple of strings. `- ` with nothing after it parses to None."""
    if value is None:
        return ()
    if not isinstance(value, list):
        return (str(value),)
    return tuple("" if v is None else str(v) for v in value)


def parse_rbac(texts: dict[str, str]) -> Corpus:
    """Every RBAC document in the YAML corpus, as rules, role identities and bindings.

    Documents are PRE-FILTERED by a top-level `kind:` before the strict parser sees them. That is
    not an optimisation: `config/` also holds CRDs and a ValidatingAdmissionPolicy whose CEL carries
    flow collections, which `yamlsubset` refuses by design, and handing it those would turn every
    run into a parse error about a file this check has no opinion on.
    """
    rules: list[Rule] = []
    generated: list[Rule] = []
    defined: set[tuple[str, str]] = set()
    bindings: list[tuple[str, str, str]] = []
    unparsed: list[str] = []

    for rel in sorted(texts):
        if not rel.endswith((".yaml", ".yml")):
            continue
        for n, doc in _documents(texts[rel]):
            if not RBAC_KIND.search(doc):
                continue
            try:
                obj = load_corpus(doc)
            except CorpusSyntaxError as exc:
                unparsed.append(
                    f"{rel} document {n} is an RBAC document this check cannot parse ({exc}). A "
                    f"document that cannot be read cannot be cleared, and clearing it by skipping "
                    f"it is how a check reports a pass over the one grant nobody could see."
                )
                continue
            kind = obj.get("kind")
            name = str((obj.get("metadata") or {}).get("name") or "(unnamed)")
            where = f"{rel} {kind}/{name}"

            if kind in ("Role", "ClusterRole"):
                defined.add((str(kind), name))
                if obj.get("aggregationRule") is not None:
                    unparsed.append(
                        f"{where} carries an `aggregationRule`. Its rules are filled in at runtime "
                        f"by the controller-manager from whatever ClusterRoles match the selector, "
                        f"so the `rules:` this check parses is not the authority the role confers "
                        f"-- an empty list here would read as 'grants nothing' and be wrong."
                    )
                for i, rule in enumerate(obj.get("rules") or []):
                    if not isinstance(rule, dict):
                        unparsed.append(f"{where} rule {i} is not a mapping: {rule!r}")
                        continue
                    if rule.get("nonResourceURLs") is not None:
                        unparsed.append(
                            f"{where} rule {i} grants `nonResourceURLs`, which this check does not "
                            f"model. A URL grant cannot reach an RBAC object, but the rule is now "
                            f"outside the parse and property 7 would silently disagree about it."
                        )
                    parsed = Rule(
                        f"{where} rule {i}",
                        _strings(rule.get("apiGroups")),
                        _strings(rule.get("resources")),
                        _strings(rule.get("verbs")),
                    )
                    rules.append(parsed)
                    if kind == "ClusterRole" and name == GENERATED_ROLE:
                        generated.append(parsed)
            else:
                ref = obj.get("roleRef") or {}
                bindings.append(
                    (where, str(ref.get("kind") or "(none)"), str(ref.get("name") or "(none)"))
                )

    return Corpus(rules, generated, defined, bindings, unparsed)


def parse_markers(texts: dict[str, str]) -> tuple[list[Rule], list[str]]:
    """Every `+kubebuilder:rbac` marker in the shipped Go source, as rules.

    `_test.go` is excluded because controller-gen's `paths="./..."` loads packages without their
    test files, so a marker there renders nothing. `resourceNames=` is read and dropped: it only
    ever NARROWS a rule, so ignoring it can make this check stricter and never laxer.
    """
    rules: list[Rule] = []
    unparsed: list[str] = []
    for rel in sorted(texts):
        if not rel.endswith(".go") or rel.endswith("_test.go"):
            continue
        for line_no, line in enumerate(texts[rel].splitlines(), 1):
            m = MARKER.match(line)
            if not m:
                continue
            where = f"{rel}:{line_no} +kubebuilder:rbac"
            fields: dict[str, str] = {}
            for field in m.group(1).split(","):
                key, sep, value = field.partition("=")
                if not sep:
                    unparsed.append(f"{where} has a field with no `=`: {field!r}")
                    continue
                fields[key] = value
            unknown = sorted(set(fields) - KNOWN_MARKER_FIELDS)
            if unknown:
                unparsed.append(
                    f"{where} carries marker field(s) {unknown} this check does not model, so the "
                    f"rule controller-gen renders from it is not the rule scanned here. "
                    f"`namespace=` in particular emits a namespaced Role into a different file "
                    f"entirely, and property 7 would report the whole marker as un-rendered."
                )
            rules.append(
                Rule(
                    where,
                    tuple(g.strip('"') for g in fields.get("groups", "").split(";")),
                    tuple(r.strip('"') for r in fields.get("resources", "").split(";")),
                    tuple(v.strip('"') for v in fields.get("verbs", "").split(";")),
                )
            )
    return rules, unparsed


def scan(rules: list[Rule]) -> list[str]:
    """Properties 2 through 6, over one rule at a time. The same scanner reads both artifacts."""
    findings: list[str] = []
    for rule in rules:
        # --- 4. wildcards, one finding per position ------------------------------------------
        if WILDCARD in rule.groups:
            findings.append(
                f"{rule.where} {SIG_WILD_GROUPS}. `*` includes {RBAC_GROUP}, so the rule grants "
                f"its verbs over RBAC itself while property 2's group scan finds nothing to name."
            )
        if WILDCARD in rule.resources:
            findings.append(
                f"{rule.where} {SIG_WILD_RESOURCES}. `*` includes `rolebindings` in whatever "
                f"group the rule names, and every resource that group grows next."
            )
        if WILDCARD in rule.verbs:
            findings.append(
                f"{rule.where} {SIG_WILD_VERBS}. `*` includes `escalate`, `bind` and "
                f"`impersonate`, none of which anybody wrote down."
            )

        for group, resource, verb in sorted(rule.triples()):
            base, slash, _sub = resource.partition("/")
            named = f"{rule.where} grants {verb!r} on {resource!r}"

            # --- 6. the three named escalation verbs, wherever they appear -------------------
            if verb in ESCALATION_VERBS:
                findings.append(
                    f"{named}: {SIG_ESCALATION}. `escalate` lifts the API server's own "
                    f"escalation-prevention check, `bind` confers any Role the holder can name, "
                    f"and `impersonate` is every identity in the cluster at once ([[LSN-004]])."
                )
                continue

            # --- 5. the allow-list, which is the bound underneath 4 and 6 --------------------
            if verb != WILDCARD and verb not in ORDINARY_VERBS:
                findings.append(
                    f"{named}: {SIG_UNLISTED} ({'/'.join(sorted(ORDINARY_VERBS))}). 09 §11.4 makes "
                    f"this an allow-list rather than a deny-list of writes precisely so a verb "
                    f"nobody anticipated is a finding on the day it arrives."
                )
                continue

            # --- 2. no verb on any RBAC resource, reads included -----------------------------
            if group == RBAC_GROUP or base in RBAC_RESOURCES:
                findings.append(
                    f"{named} in API group {group or '(core)'!r}: {SIG_RBAC}, reads included -- "
                    f"the 'beyond `get;list;watch`' clause attaches to ServiceAccounts alone. A "
                    f"controller that can write RBAC can grant an agent whatever it likes at "
                    f"runtime, and no check of the rendered templates would ever see it."
                )
                continue

            # --- 3. identity resources, read-only, subresources untouchable ------------------
            if base in IDENTITY_RESOURCES:
                if slash:
                    findings.append(
                        f"{named}: {SIG_SUBRESOURCE}. `serviceaccounts/token` returns a bearer "
                        f"token for that SA and `certificatesigningrequests/approval` signs a "
                        f"client certificate; either one is the credential itself, not a "
                        f"reference to it."
                    )
                elif verb not in READ_VERBS:
                    findings.append(
                        f"{named}: {SIG_IDENTITY} -- {IDENTITY_RESOURCES[base]}. 08 §2.7's 'May "
                        f"not' list names ServiceAccount alongside the four RBAC kinds, because "
                        f"the two halves of minting authority are the identity and the grant."
                    )
    return findings


def check(rbac_texts: dict[str, str], go_texts: dict[str, str], probe_doc: str) -> list[str]:
    corpus = parse_rbac(rbac_texts)
    markers, marker_errors = parse_markers(go_texts)

    # --- 1. non-vacuity ------------------------------------------------------------------------
    vacuous: list[str] = []
    roles = len({name for _kind, name in corpus.defined})
    if roles < MIN_ROLES:
        vacuous.append(
            f"VACUOUS: {CONFIG_TREE}/ yielded {roles} Role/ClusterRole document(s); there were 4 "
            f"when this was written. Every property below is a scan, and a scan over an empty "
            f"corpus is indistinguishable from a control plane that grants nothing."
        )
    if len(corpus.rules) < MIN_RULES:
        vacuous.append(
            f"VACUOUS: {CONFIG_TREE}/ yielded {len(corpus.rules)} rule(s), under the floor of "
            f"{MIN_RULES}. Either the roles shrank by two thirds or the rule scan stopped seeing "
            f"them, and those two look identical from a green run."
        )
    if (("ClusterRole", GENERATED_ROLE)) not in corpus.defined:
        vacuous.append(
            f"VACUOUS: no ClusterRole named {GENERATED_ROLE!r} was parsed out of {CONFIG_TREE}/. "
            f"That is the ClusterRole 09 §6 and 08 §7 both name, and property 7 compares it -- and "
            f"only it -- against the markers, so its absence retires two properties in silence."
        )
    if len(markers) < MIN_MARKERS:
        vacuous.append(
            f"VACUOUS: {len(markers)} `+kubebuilder:rbac` marker(s) found under {GO_TREE}/, under "
            f"the floor of {MIN_MARKERS}. The markers are the half a developer edits; with none of "
            f"them read, property 7 would report the whole generated ClusterRole as hand-written."
        )
    probe_corpus = parse_rbac({"(probe)/self-test.yaml": probe_doc})
    probe_found = scan(probe_corpus.rules)
    missing = [s for s in PROBE_SIGNALS if not any(s in f for f in probe_found)]
    if probe_corpus.unparsed or not probe_corpus.rules or missing:
        vacuous.append(
            f"VACUOUS: the rule scanner cleared the probe document. It is nothing but violations "
            f"-- {len(probe_corpus.rules)} rule(s) parsed, {len(probe_found)} finding(s) produced "
            f"-- and it did not produce {missing or 'a parse'}. A scanner that no longer "
            f"recognises an RBAC rule when shown one reports the whole tree clean."
        )
    if vacuous:
        return vacuous

    findings: list[str] = list(corpus.unparsed) + list(marker_errors)

    # --- 2-6, over both artifacts --------------------------------------------------------------
    findings += scan(corpus.rules)
    findings += scan(markers)

    # --- 7. the two artifacts agree, triple for triple -----------------------------------------
    rendered_triples = {t for r in corpus.generated for t in r.triples()}
    marker_triples = {t for r in markers for t in r.triples()}
    for group, resource, verb in sorted(marker_triples - rendered_triples):
        findings.append(
            f"{group or '(core)'}/{resource}:{verb} {SIG_MARKER_ONLY}. `make manifests` was not "
            f"run, so the grant is invisible in every YAML in this branch and lands the moment CI "
            f"regenerates -- in a commit that will look like formatting."
        )
    for group, resource, verb in sorted(rendered_triples - marker_triples):
        findings.append(
            f"{group or '(core)'}/{resource}:{verb} {SIG_RENDER_ONLY}. `config/rbac/role.yaml` is "
            f"generated; a hand-edit either ships un-reviewed or is deleted by the next `make "
            f"manifests`, and neither outcome is the one the editor intended."
        )

    # --- 8. no binding reaches outside the corpus ----------------------------------------------
    for where, ref_kind, ref_name in corpus.bindings:
        if (ref_kind, ref_name) not in corpus.defined:
            findings.append(
                f"{where} roleRef names {ref_kind}/{ref_name}, {SIG_DANGLING_REF}. A binding to a "
                f"built-in -- `cluster-admin`, `edit` -- confers its authority with no rule in "
                f"this tree for any property above to read."
            )

    # --- 9. no shipped Go file constructs an RBAC object ---------------------------------------
    for rel in sorted(go_texts):
        if not rel.endswith(".go") or rel.endswith("_test.go"):
            continue
        if GO_RBAC_IMPORT.search(go_texts[rel]):
            findings.append(
                f"{rel} {SIG_GO_IMPORT}/v1, the typed RBAC API. 08 §2.7: the controller consumes "
                f"identity and never produces it, and the only reason to import this package is "
                f"to build a Role or a RoleBinding. RBAC is the bound; this is the grep half of "
                f"08 §7 that says nobody even tried."
            )

    return findings


def _inputs() -> tuple[dict[str, str], dict[str, str], str]:
    rbac_texts = read_repo_files(REPO, CONFIG_TREE)
    go_texts = {
        rel: text
        for rel, text in read_repo_files(REPO, GO_TREE).items()
        if rel.endswith(".go")
    }
    if not rbac_texts:
        raise SystemExit(f"FAIL: {CONFIG_TREE}/ enumerated no files")
    if not go_texts:
        raise SystemExit(f"FAIL: {GO_TREE}/ enumerated no Go files")
    return rbac_texts, go_texts, PROBE_ROLE


def run() -> int:
    inputs = _inputs()
    findings = check(*inputs)
    if findings:
        print("FAIL: V-CTN-017 -- the control plane's RBAC can mint RBAC", file=sys.stderr)
        for f in findings:
            print(f"  - {f}", file=sys.stderr)
        return 1
    corpus = parse_rbac(inputs[0])
    markers, _ = parse_markers(inputs[1])
    grants = sum(len(r.triples()) for r in corpus.rules)
    print(
        f"PASS: V-CTN-017 (L0) -- {len(corpus.defined)} control-plane Role/ClusterRole(s) under "
        f"{CONFIG_TREE}/, {len(corpus.rules)} rule(s) and {grants} (group, resource, verb) "
        f"grant(s), carry no verb on RBAC objects, no write on an identity resource, no wildcard "
        f"in any position and no escalate/bind/impersonate; {len(markers)} +kubebuilder:rbac "
        f"marker(s) agree with {GENERATED_ROLE} triple for triple; all "
        f"{len(corpus.bindings)} roleRef(s) resolve inside the tree; no shipped Go file imports "
        f"the RBAC API"
    )
    return 0


def _mutate(base: tuple[dict[str, str], dict[str, str], str], index: int, fn):
    out = list(base)
    out[index] = fn(out[index])
    return (out[0], out[1], out[2])


def _edit(path: str, old: str, new: str):
    """A corpus transform that rewrites one occurrence in one file and nothing else.

    A path that is not in the corpus leaves it untouched, which the `args == base` guard below
    scores BROKEN. That is the intended behaviour: a mutation anchored on a file that moved must
    not be reported as a MISS against the property it was aimed at ([[LSN-063]]).
    """

    def apply(corpus: dict[str, str]) -> dict[str, str]:
        out = dict(corpus)
        if path in out:
            out[path] = out[path].replace(old, new, 1)
        return out

    return apply


def _blank(path: str):
    def apply(corpus: dict[str, str]) -> dict[str, str]:
        out = dict(corpus)
        if path in out:
            out[path] = ""
        return out

    return apply


ROLE = "k8s-operator/config/rbac/role.yaml"
BRAKE_ROLE = "k8s-operator/config/rbac/brake_role.yaml"
ROUTER_ROLE = "k8s-operator/config/router/role.yaml"
BINDING = "k8s-operator/config/rbac/role_binding.yaml"
CONTROLLER_GO = "k8s-operator/internal/controller/agent_controller.go"
UNDO_GO = "k8s-operator/internal/controller/undo_controller.go"

# The rule the generated ClusterRole ends on. Several mutations splice a new rule in ahead of it.
LAST_RULE = "  - apiGroups:\n      - node.k8s.io\n"


def negative_control() -> int:
    """Twenty-one ways this check could go quiet, each naming the signal it must produce.

    One row per property, plus a row per direction where a property has two (7), plus a row per
    position where it has three (4). Three of the twenty-one deliberately land outside
    `config/rbac/role.yaml` -- in the hand-written brake role, in the router's, and in a Go marker
    -- because the corpus is DISCOVERED, and a discovery that quietly narrowed to the one generated
    file would still pass every other row here ([[LSN-036]]).
    """
    base = _inputs()
    findings = check(*base)
    if findings:
        print("  BROKEN   the tree is not green, so no row below can be attributed")
        for f in findings[:4]:
            print(f"           {f}")
        print("FAIL: V-CTN-017 negative control -- 0 mutations evaluated")
        return 1

    mutations = [
        (
            "the generated ClusterRole gains `create` on rolebindings",
            _mutate(base, 0, _edit(
                ROLE,
                LAST_RULE,
                "  - apiGroups:\n      - rbac.authorization.k8s.io\n"
                "    resources:\n      - rolebindings\n"
                "    verbs:\n      - create\n" + LAST_RULE,
            )),
            f"grants 'create' on 'rolebindings' in API group 'rbac.authorization.k8s.io': {SIG_RBAC}",
        ),
        (
            "the router's ClusterRole gains READ on roles -- a read verb on RBAC is still a finding",
            _mutate(base, 0, _edit(
                ROUTER_ROLE,
                "rules:\n",
                "rules:\n"
                "  - apiGroups:\n      - rbac.authorization.k8s.io\n"
                "    resources:\n      - roles\n"
                "    verbs:\n      - get\n      - list\n      - watch\n",
            )),
            f"grants 'get' on 'roles' in API group 'rbac.authorization.k8s.io': {SIG_RBAC}",
        ),
        (
            "serviceaccounts moves into the CRUD rule, so the controller can mint an identity",
            _mutate(base, 0, _edit(
                ROLE,
                "      - persistentvolumeclaims\n      - services\n",
                "      - persistentvolumeclaims\n      - serviceaccounts\n      - services\n",
            )),
            f"grants 'create' on 'serviceaccounts': {SIG_IDENTITY}",
        ),
        (
            "the controller gains `create` on serviceaccounts/token -- the credential itself",
            _mutate(base, 0, _edit(
                ROLE,
                LAST_RULE,
                '  - apiGroups:\n      - ""\n'
                "    resources:\n      - serviceaccounts/token\n"
                "    verbs:\n      - create\n" + LAST_RULE,
            )),
            f"grants 'create' on 'serviceaccounts/token': {SIG_SUBRESOURCE}",
        ),
        (
            "an apiGroups list becomes `*`, which silently includes rbac.authorization.k8s.io",
            _mutate(base, 0, _edit(ROLE, "      - apiextensions.k8s.io\n", '      - "*"\n')),
            SIG_WILD_GROUPS,
        ),
        (
            "a resources list becomes `*`",
            _mutate(base, 0, _edit(ROLE, "      - runtimeclasses\n", '      - "*"\n')),
            SIG_WILD_RESOURCES,
        ),
        (
            "a verbs list becomes `*`",
            _mutate(base, 0, _edit(
                ROLE,
                "      - customresourcedefinitions\n    verbs:\n      - get\n      - list\n",
                '      - customresourcedefinitions\n    verbs:\n      - "*"\n',
            )),
            SIG_WILD_VERBS,
        ),
        (
            "`escalate` is added to an ordinary rule, where it is not a write and reads as one",
            _mutate(base, 0, _edit(
                ROLE,
                "      - customresourcedefinitions\n    verbs:\n      - get\n",
                "      - customresourcedefinitions\n    verbs:\n      - escalate\n      - get\n",
            )),
            f"grants 'escalate' on 'customresourcedefinitions': {SIG_ESCALATION}",
        ),
        (
            "`impersonate` on serviceaccounts -- cluster-admin, on a core resource",
            _mutate(base, 0, _edit(
                ROLE,
                LAST_RULE,
                '  - apiGroups:\n      - ""\n'
                "    resources:\n      - serviceaccounts\n"
                "    verbs:\n      - impersonate\n" + LAST_RULE,
            )),
            f"grants 'impersonate' on 'serviceaccounts': {SIG_ESCALATION}",
        ),
        (
            "a verb nobody anticipated arrives, and the allow-list is what has to catch it",
            _mutate(base, 0, _edit(
                ROLE,
                "      - runtimeclasses\n    verbs:\n      - get\n",
                "      - runtimeclasses\n    verbs:\n      - approve\n      - get\n",
            )),
            f"grants 'approve' on 'runtimeclasses': {SIG_UNLISTED}",
        ),
        (
            "the controller gains the CSR approval subresource",
            _mutate(base, 0, _edit(
                ROLE,
                LAST_RULE,
                "  - apiGroups:\n      - certificates.k8s.io\n"
                "    resources:\n      - certificatesigningrequests/approval\n"
                "    verbs:\n      - update\n" + LAST_RULE,
            )),
            f"grants 'update' on 'certificatesigningrequests/approval': {SIG_SUBRESOURCE}",
        ),
        (
            "the HAND-WRITTEN brake role gains `bind`, where no marker and no generator can see it",
            _mutate(base, 0, _edit(
                BRAKE_ROLE,
                "      - agents\n    verbs:\n      - get\n",
                "      - agents\n    verbs:\n      - bind\n      - get\n",
            )),
            f"grants 'bind' on 'agents': {SIG_ESCALATION}",
        ),
        (
            "a new +kubebuilder:rbac marker grants escalate -- the Go half is scanned too",
            _mutate(base, 1, _edit(
                UNDO_GO,
                "// +kubebuilder:rbac:groups=kubeagents.x-k8s.io,resources=undorequests,verbs=get;list;watch\n",
                "// +kubebuilder:rbac:groups=kubeagents.x-k8s.io,resources=undorequests,verbs=get;list;watch\n"
                "// +kubebuilder:rbac:groups=rbac.authorization.k8s.io,resources=rolebindings,verbs=escalate\n",
            )),
            f"grants 'escalate' on 'rolebindings': {SIG_ESCALATION}",
        ),
        (
            "a marker widens serviceaccounts and `make manifests` is not run",
            _mutate(base, 1, _edit(
                CONTROLLER_GO,
                '// +kubebuilder:rbac:groups="",resources=serviceaccounts,verbs=get;list;watch\n',
                '// +kubebuilder:rbac:groups="",resources=serviceaccounts,verbs=get;list;watch;create\n',
            )),
            f"(core)/serviceaccounts:create {SIG_MARKER_ONLY}",
        ),
        (
            "the generated ClusterRole is hand-edited with a grant no marker declares",
            _mutate(base, 0, _edit(
                ROLE,
                LAST_RULE,
                "  - apiGroups:\n      - coordination.k8s.io\n"
                "    resources:\n      - leases\n"
                "    verbs:\n      - get\n" + LAST_RULE,
            )),
            f"coordination.k8s.io/leases:get {SIG_RENDER_ONLY}",
        ),
        (
            "the generated ClusterRole goes stale against a marker that still declares the verb",
            _mutate(base, 0, _edit(
                ROLE,
                "      - customresourcedefinitions\n    verbs:\n      - get\n      - list\n",
                "      - customresourcedefinitions\n    verbs:\n      - get\n",
            )),
            f"apiextensions.k8s.io/customresourcedefinitions:list {SIG_MARKER_ONLY}",
        ),
        (
            "the ClusterRoleBinding is repointed at cluster-admin, leaving no rule to read",
            _mutate(base, 0, _edit(BINDING, "  name: manager-role\n", "  name: cluster-admin\n")),
            f"roleRef names ClusterRole/cluster-admin, {SIG_DANGLING_REF}",
        ),
        (
            "a shipped Go file imports the typed RBAC API",
            _mutate(base, 1, _edit(
                CONTROLLER_GO,
                '\tnodev1 "k8s.io/api/node/v1"\n',
                '\tnodev1 "k8s.io/api/node/v1"\n\trbacv1 "k8s.io/api/rbac/v1"\n',
            )),
            f"{CONTROLLER_GO} {SIG_GO_IMPORT}",
        ),
        (
            "the generated ClusterRole becomes an aggregated one, whose rules arrive at runtime",
            _mutate(base, 0, _edit(
                ROLE,
                "rules:\n",
                "aggregationRule:\n  clusterRoleSelectors:\n    - matchLabels:\n"
                '        rbac.authorization.k8s.io/aggregate-to-edit: "true"\n'
                "rules:\n",
            )),
            "carries an `aggregationRule`",
        ),
        (
            "the generated ClusterRole is emptied, so every scan below it has nothing to scan",
            _mutate(base, 0, _blank(ROLE)),
            f"VACUOUS: no ClusterRole named {GENERATED_ROLE!r} was parsed",
        ),
        (
            "the scanner's own probe is swapped for a harmless role, blinding the self-test",
            _mutate(base, 2, lambda _: (
                "kind: ClusterRole\nmetadata:\n  name: harmless\n"
                'rules:\n  - apiGroups:\n      - ""\n'
                "    resources:\n      - pods\n    verbs:\n      - get\n"
            )),
            "VACUOUS: the rule scanner cleared the probe document",
        ),
    ]

    failures = 0
    for name, args, needle in mutations:
        # A mutation that did not change its input cannot be evaluated: the unmutated base is
        # re-checked, comes back clean, and the row prints MISS -- the verdict for "the check let
        # the defect through" -- over a defect that was never applied ([[LSN-063]]).
        if args == base:
            failures += 1
            print(f"  BROKEN  {name}")
            print("           the mutation did not change its input; nothing was evaluated")
            continue
        found = check(*args)
        hit = any(needle in f for f in found)
        print(f"  {'caught ' if hit else 'MISS   '} {name}")
        if not hit:
            failures += 1
            print(f"           expected a finding containing {needle!r}; got {found[:2] or 'none'}")
    print(
        f"{'PASS' if not failures else 'FAIL'}: V-CTN-017 negative control -- "
        f"{len(mutations) - failures}/{len(mutations)} mutations caught, across the generated "
        f"ClusterRole, the hand-written ones and the markers"
    )
    return 1 if failures else 0


def main(argv: list[str]) -> int:
    if "--negative-control" in argv:
        return negative_control()
    return run()


if __name__ == "__main__":
    sys.exit(main(sys.argv[1:]))
