/*
Copyright 2026.

Licensed under the Apache License, Version 2.0 (the "License");
you may not use this file except in compliance with the License.
You may obtain a copy of the License at

    http://www.apache.org/licenses/LICENSE-2.0

Unless required by applicable law or agreed to in writing, software
distributed under the License is distributed on an "AS IS" BASIS,
WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
See the License for the specific language governing permissions and
limitations under the License.
*/

package execute_test

import (
	"context"
	"os"
	"testing"

	apierrors "k8s.io/apimachinery/pkg/api/errors"
	metav1 "k8s.io/apimachinery/pkg/apis/meta/v1"
	"k8s.io/apimachinery/pkg/apis/meta/v1/unstructured"
	"k8s.io/apimachinery/pkg/runtime"
	clientgoscheme "k8s.io/client-go/kubernetes/scheme"
	"sigs.k8s.io/controller-runtime/pkg/client"
	"sigs.k8s.io/controller-runtime/pkg/envtest"

	agentv1alpha1 "github.com/gke-labs/kube-agents/k8s-operator/api/v1alpha1"
	"github.com/gke-labs/kube-agents/k8s-operator/internal/broker/execute"
)

// The properties in this file are the ones a fake cannot establish.
//
// Everywhere else in this package the Applier is a seam and the tests assert on what the executor
// DOES with the answers it gets. Three claims are not like that -- they are claims about what a real
// API server does:
//
//   - the field manager appears in metadata.managedFields exactly as `kube-agents/<tier>/<scope>`
//     (V-BRK-006). A fake can only confirm the string was passed down; whether the server records it
//     verbatim, lowercases it, or rejects it is the server's business.
//   - a dry-run apply leaves nothing behind (V-BRK-019). The whole value of dry-run rests on this,
//     and a fake that returns an object without writing one proves only that the fake does not write.
//   - server-side apply reports a conflict when another manager owns the field. That conflict is what
//     `contested` is built on, and it is generated by the API server's field-ownership tracking --
//     there is nothing in this repository that could produce it.
//
// envtest is L1 by binding.md §Targets: a real API server, process-local, no cluster. The L2
// instances of these checks still require gke-scratch-kube-agents-dev.

func startEnv(t *testing.T) client.Client {
	t.Helper()
	if os.Getenv("KUBEBUILDER_ASSETS") == "" {
		t.Skip("KUBEBUILDER_ASSETS unset; run via `make test` to exercise the executor against a real API server")
	}

	scheme := runtime.NewScheme()
	if err := clientgoscheme.AddToScheme(scheme); err != nil {
		t.Fatalf("add clientgo scheme: %v", err)
	}

	testEnv := &envtest.Environment{Scheme: scheme}
	cfg, err := testEnv.Start()
	if err != nil {
		t.Fatalf("start envtest: %v", err)
	}
	t.Cleanup(func() { _ = testEnv.Stop() })

	k8s, err := client.New(cfg, client.Options{Scheme: scheme})
	if err != nil {
		t.Fatalf("new client: %v", err)
	}
	return k8s
}

func cmRef(name string) agentv1alpha1.TargetRef {
	return agentv1alpha1.TargetRef{Version: "v1", Kind: "ConfigMap", Namespace: "default", Name: name}
}

func desiredCM(name string, data map[string]any) *unstructured.Unstructured {
	return &unstructured.Unstructured{Object: map[string]any{
		"apiVersion": "v1",
		"kind":       "ConfigMap",
		"metadata":   map[string]any{"name": name, "namespace": "default"},
		"data":       data,
	}}
}

// journalStub stands in for durability. The write-ahead ORDER is proven in apply_test.go against a
// recording fake; here the record's contents are not the subject.
type journalStub struct{}

func (journalStub) ConfirmDurable(context.Context, string) error { return nil }

func managersOf(obj *unstructured.Unstructured) []string {
	var out []string
	for _, f := range obj.GetManagedFields() {
		out = append(out, f.Manager)
	}
	return out
}

func TestFieldManagerIsRecordedVerbatim(t *testing.T) {
	k8s := startEnv(t)
	ctx := context.Background()

	applier := &execute.ClientApplier{Client: k8s}
	reader := &execute.ClientReader{Client: k8s}
	e := &execute.Executor{Applier: applier, Journal: journalStub{}}

	name := "fm-verbatim"
	snaps, err := execute.CaptureAll(ctx, reader, "act-1", []agentv1alpha1.TargetRef{cmRef(name)}, metav1.Now(), nil)
	if err != nil {
		t.Fatalf("CaptureAll: %v", err)
	}
	if snaps[0].Existed {
		t.Fatal("the target already exists")
	}

	desired := desiredCM(name, map[string]any{"k": "v"})
	if _, err := e.Execute(ctx, execute.Request{
		ActionID:      "act-1",
		AgentIdentity: "cluster-admin/prod-usc1",
		Ops: []execute.Op{{
			Index:      0,
			Verb:       "create",
			Ref:        cmRef(name),
			Desired:    desired,
			Classified: execute.Classified{TargetIndex: 0, Verb: "create", WholeObject: true},
		}},
		Snapshots: snaps,
	}); err != nil {
		t.Fatalf("Execute: %v", err)
	}

	live := &unstructured.Unstructured{}
	live.SetAPIVersion("v1")
	live.SetKind("ConfigMap")
	if err := k8s.Get(ctx, client.ObjectKey{Namespace: "default", Name: name}, live); err != nil {
		t.Fatalf("get: %v", err)
	}

	managers := managersOf(live)
	found := false
	for _, m := range managers {
		if m == "kube-agents/cluster-admin/prod-usc1" {
			found = true
		}
	}
	if !found {
		t.Fatalf("managedFields = %v, want it to contain %q exactly", managers, "kube-agents/cluster-admin/prod-usc1")
	}
	// And the inverse the ownership comparison depends on.
	for _, m := range managers {
		if execute.IsAgentManager(m) && execute.AgentIdentityOfManager(m) != "cluster-admin/prod-usc1" {
			t.Fatalf("manager %q inverts to %q", m, execute.AgentIdentityOfManager(m))
		}
	}
}

func TestDryRunLeavesNothingBehind(t *testing.T) {
	k8s := startEnv(t)
	ctx := context.Background()

	applier := &execute.ClientApplier{Client: k8s}
	reader := &execute.ClientReader{Client: k8s}
	e := &execute.Executor{Applier: applier, Journal: journalStub{}}

	name := "dry-run-only"
	snaps, err := execute.CaptureAll(ctx, reader, "act-2", []agentv1alpha1.TargetRef{cmRef(name)}, metav1.Now(), nil)
	if err != nil {
		t.Fatalf("CaptureAll: %v", err)
	}

	res, err := e.Execute(ctx, execute.Request{
		ActionID:      "act-2",
		AgentIdentity: "platform",
		DryRunOnly:    true,
		Ops: []execute.Op{{
			Index:      0,
			Verb:       "create",
			Ref:        cmRef(name),
			Desired:    desiredCM(name, map[string]any{"k": "v"}),
			Classified: execute.Classified{TargetIndex: 0, Verb: "create", WholeObject: true},
		}},
		Snapshots: snaps,
	})
	if err != nil {
		t.Fatalf("Execute: %v", err)
	}
	if len(res.Outcomes[0].Diff.Ops) == 0 {
		t.Fatal("the dry run produced no diff; a shadow-mode record with no diff says nothing")
	}

	live := &unstructured.Unstructured{}
	live.SetAPIVersion("v1")
	live.SetKind("ConfigMap")
	err = k8s.Get(ctx, client.ObjectKey{Namespace: "default", Name: name}, live)
	if !apierrors.IsNotFound(err) {
		t.Fatalf("after a dry run the object exists (err = %v); dry-run is not a mode, it is a promise", err)
	}
}

func TestForeignManagerConflictSurfaces(t *testing.T) {
	// Another manager owns the field. Server-side apply must report a conflict rather than take it:
	// forcing ownership would resolve `contested` by making it never happen.
	k8s := startEnv(t)
	ctx := context.Background()

	name := "contested-cm"
	foreign := desiredCM(name, map[string]any{"k": "theirs"})
	if err := k8s.Patch(ctx, foreign, client.Apply, client.FieldOwner("some-other-controller")); err != nil {
		t.Fatalf("seed apply: %v", err)
	}

	applier := &execute.ClientApplier{Client: k8s}
	reader := &execute.ClientReader{Client: k8s}
	e := &execute.Executor{Applier: applier, Journal: journalStub{}}

	snaps, err := execute.CaptureAll(ctx, reader, "act-3", []agentv1alpha1.TargetRef{cmRef(name)}, metav1.Now(), nil)
	if err != nil {
		t.Fatalf("CaptureAll: %v", err)
	}
	if !snaps[0].Existed {
		t.Fatal("the seeded object was not found")
	}

	res, err := e.Execute(ctx, execute.Request{
		ActionID:      "act-3",
		AgentIdentity: "cluster-admin/prod",
		Ops: []execute.Op{{
			Index:   0,
			Verb:    "apply",
			Ref:     cmRef(name),
			Desired: desiredCM(name, map[string]any{"k": "ours"}),
			Classified: execute.Classified{
				TargetIndex:  0,
				Verb:         "apply",
				TouchedPaths: []string{"/data/k"},
			},
		}},
		Snapshots: snaps,
	})
	if err == nil {
		t.Fatal("an apply over a field owned by another manager succeeded; ownership was forced")
	}
	if !apierrors.IsConflict(errCause(err)) {
		t.Fatalf("want a conflict from the API server, got: %v", err)
	}
	if res.Mutated {
		// The conflict is raised by the dry run, before the write-ahead journal and before any
		// mutation -- which is the ordering the whole of apply.go exists to guarantee.
		t.Fatal("Mutated = true for an action the dry run rejected")
	}

	live := &unstructured.Unstructured{}
	live.SetAPIVersion("v1")
	live.SetKind("ConfigMap")
	if err := k8s.Get(ctx, client.ObjectKey{Namespace: "default", Name: name}, live); err != nil {
		t.Fatalf("get: %v", err)
	}
	data, _, _ := unstructured.NestedStringMap(live.Object, "data")
	if data["k"] != "theirs" {
		t.Fatalf("data.k = %q; the rejected apply changed the object anyway", data["k"])
	}
}

// errCause unwraps to the deepest error, so an apierrors predicate can be applied to a wrapped one.
func errCause(err error) error {
	for {
		u, ok := err.(interface{ Unwrap() error })
		if !ok {
			return err
		}
		next := u.Unwrap()
		if next == nil {
			return err
		}
		err = next
	}
}

func TestExecutedDiffComesFromTheServer(t *testing.T) {
	// The V-BRK-020 foundation, against a real merge: the executed diff must describe the SERVER's
	// object, not the payload. The evidence is a field the payload never mentions -- here the
	// defaults a Deployment picks up (`spec.revisionHistoryLimit`, `spec.strategy`,
	// `spec.progressDeadlineSeconds`). If the diff were computed from the submitted desired state,
	// none of them would be in it, and an expanding merge would be equally invisible.
	//
	// A server-assigned METADATA field would not do: `uid`, `resourceVersion` and `creationTimestamp`
	// are all on the sanitizer's DROP list, so their absence proves nothing either way.
	k8s := startEnv(t)
	ctx := context.Background()

	applier := &execute.ClientApplier{Client: k8s}
	reader := &execute.ClientReader{Client: k8s}
	e := &execute.Executor{Applier: applier, Journal: journalStub{}}

	ref := agentv1alpha1.TargetRef{Group: "apps", Version: "v1", Kind: "Deployment", Namespace: "default", Name: "server-diff"}
	snaps, err := execute.CaptureAll(ctx, reader, "act-4", []agentv1alpha1.TargetRef{ref}, metav1.Now(), nil)
	if err != nil {
		t.Fatalf("CaptureAll: %v", err)
	}

	desired := &unstructured.Unstructured{Object: map[string]any{
		"apiVersion": "apps/v1",
		"kind":       "Deployment",
		"metadata":   map[string]any{"name": "server-diff", "namespace": "default"},
		"spec": map[string]any{
			"replicas": int64(1),
			"selector": map[string]any{"matchLabels": map[string]any{"app": "server-diff"}},
			"template": map[string]any{
				"metadata": map[string]any{"labels": map[string]any{"app": "server-diff"}},
				"spec": map[string]any{
					"containers": []any{map[string]any{"name": "c", "image": "registry.k8s.io/pause:3.9"}},
				},
			},
		},
	}}

	res, err := e.Execute(ctx, execute.Request{
		ActionID:      "act-4",
		AgentIdentity: "platform",
		Ops: []execute.Op{{
			Index:      0,
			Verb:       "create",
			Ref:        ref,
			Desired:    desired,
			Classified: execute.Classified{TargetIndex: 0, Verb: "create", WholeObject: true},
		}},
		Snapshots: snaps,
	})
	if err != nil {
		t.Fatalf("Execute: %v", err)
	}

	got := res.Outcomes[0].Diff.Pointers()
	defaulted := map[string]bool{}
	for _, p := range got {
		defaulted[p] = true
	}
	for _, want := range []string{"/spec/revisionHistoryLimit", "/spec/progressDeadlineSeconds"} {
		if !defaulted[want] {
			t.Fatalf("the executed diff has no %s, a field the payload never set; it may be describing the payload rather than the server's answer:\n%v", want, got)
		}
	}
	if !res.Outcomes[0].DryRunUsed {
		t.Fatal("DryRunUsed = false against an API server that supports it")
	}
}

func TestScaleTouchesOnlyReplicas(t *testing.T) {
	k8s := startEnv(t)
	ctx := context.Background()

	dep := &unstructured.Unstructured{Object: map[string]any{
		"apiVersion": "apps/v1",
		"kind":       "Deployment",
		"metadata":   map[string]any{"name": "scale-me", "namespace": "default"},
		"spec": map[string]any{
			"replicas": int64(1),
			"selector": map[string]any{"matchLabels": map[string]any{"app": "scale-me"}},
			"template": map[string]any{
				"metadata": map[string]any{"labels": map[string]any{"app": "scale-me"}},
				"spec": map[string]any{
					"containers": []any{map[string]any{"name": "c", "image": "registry.k8s.io/pause:3.9"}},
				},
			},
		},
	}}
	if err := k8s.Create(ctx, dep); err != nil {
		t.Fatalf("create deployment: %v", err)
	}

	ref := agentv1alpha1.TargetRef{Group: "apps", Version: "v1", Kind: "Deployment", Namespace: "default", Name: "scale-me"}
	applier := &execute.ClientApplier{Client: k8s}
	reader := &execute.ClientReader{Client: k8s}
	e := &execute.Executor{Applier: applier, Journal: journalStub{}}

	snaps, err := execute.CaptureAll(ctx, reader, "act-5", []agentv1alpha1.TargetRef{ref}, metav1.Now(), nil)
	if err != nil {
		t.Fatalf("CaptureAll: %v", err)
	}

	three := int32(3)
	res, err := e.Execute(ctx, execute.Request{
		ActionID:      "act-5",
		AgentIdentity: "cluster-admin/prod",
		Ops: []execute.Op{{
			Index:      0,
			Verb:       "scale",
			Ref:        ref,
			Replicas:   &three,
			Classified: execute.Classified{TargetIndex: 0, Verb: "scale", TouchedPaths: []string{"/spec/replicas"}},
		}},
		Snapshots: snaps,
	})
	if err != nil {
		t.Fatalf("Execute: %v", err)
	}

	// The classified path set is exactly `/spec/replicas`, so the integrity check passing IS the
	// assertion that the scale subresource touched nothing else. Recorded here as an explicit check
	// too, because "the check passed" and "the check ran" are different claims.
	got := res.Outcomes[0].Diff.Pointers()
	for _, p := range got {
		if p != "/spec/replicas" {
			t.Fatalf("the executed diff touches %s; a scale changed something other than the replica count:\n%v", p, got)
		}
	}
	if len(got) != 1 {
		t.Fatalf("the executed diff is %v, want exactly the replica change", got)
	}

	live := &unstructured.Unstructured{}
	live.SetAPIVersion("apps/v1")
	live.SetKind("Deployment")
	if err := k8s.Get(ctx, client.ObjectKey{Namespace: "default", Name: "scale-me"}, live); err != nil {
		t.Fatalf("get: %v", err)
	}
	n, _, _ := unstructured.NestedInt64(live.Object, "spec", "replicas")
	if n != 3 {
		t.Fatalf("replicas = %d, want 3", n)
	}
}

func TestDeleteRefusesAReplacedObject(t *testing.T) {
	// The UID precondition. Deleting by name races with a recreate, and the object the broker
	// snapshotted is not the object it would otherwise remove.
	k8s := startEnv(t)
	ctx := context.Background()

	name := "recreated"
	first := desiredCM(name, map[string]any{"k": "first"})
	if err := k8s.Create(ctx, first); err != nil {
		t.Fatalf("create: %v", err)
	}

	reader := &execute.ClientReader{Client: k8s}
	snaps, err := execute.CaptureAll(ctx, reader, "act-6", []agentv1alpha1.TargetRef{cmRef(name)}, metav1.Now(), nil)
	if err != nil {
		t.Fatalf("CaptureAll: %v", err)
	}

	// Somebody replaces it between the snapshot and the delete.
	if err := k8s.Delete(ctx, first); err != nil {
		t.Fatalf("delete: %v", err)
	}
	second := desiredCM(name, map[string]any{"k": "second"})
	if err := k8s.Create(ctx, second); err != nil {
		t.Fatalf("recreate: %v", err)
	}

	e := &execute.Executor{Applier: &execute.ClientApplier{Client: k8s}, Journal: journalStub{}}
	_, err = e.Execute(ctx, execute.Request{
		ActionID:      "act-6",
		AgentIdentity: "platform",
		Ops: []execute.Op{{
			Index:      0,
			Verb:       "delete",
			Ref:        snaps[0].Ref,
			Classified: execute.Classified{TargetIndex: 0, Verb: "delete", WholeObject: true},
		}},
		Snapshots: snaps,
	})
	if err == nil {
		t.Fatal("the delete removed an object that had been replaced since the snapshot")
	}

	live := &unstructured.Unstructured{}
	live.SetAPIVersion("v1")
	live.SetKind("ConfigMap")
	if err := k8s.Get(ctx, client.ObjectKey{Namespace: "default", Name: name}, live); err != nil {
		t.Fatalf("the replacement object was deleted: %v", err)
	}
	data, _, _ := unstructured.NestedStringMap(live.Object, "data")
	if data["k"] != "second" {
		t.Fatalf("data.k = %q, want the replacement to be untouched", data["k"])
	}
}
