apiVersion: v1
kind: ServiceAccount
metadata:
  labels:
    app.kubernetes.io/name: kube-agents-operator
    app.kubernetes.io/component: kage-router
    app.kubernetes.io/managed-by: kustomize
  name: router
  namespace: system
