//go:build !ignore_autogenerated

/*
Copyright 2026.

Licensed under the Apache License, Version 2.0 (the "License");
you may not use this file except in compliance with the License.
You may obtain a copy of the License at

    http://www.apache.org/licenses/LICENSE-2.0

Unless required by applicable law or agreed to in writing, software
distributed under the License is distributed on an "AS IS" BASIS,
WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
See the License for the specific language governing permissions and
limitations under the License.
*/

// Code generated by controller-gen. DO NOT EDIT.

package v1alpha1

import (
	"k8s.io/api/core/v1"
	metav1 "k8s.io/apimachinery/pkg/apis/meta/v1"
	"k8s.io/apimachinery/pkg/runtime"
)

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *ActionApprovals) DeepCopyInto(out *ActionApprovals) {
	*out = *in
	if in.Granted != nil {
		in, out := &in.Granted, &out.Granted
		*out = make([]ApprovalEntry, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
	if in.Rejected != nil {
		in, out := &in.Rejected, &out.Rejected
		*out = make([]ApprovalEntry, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
	if in.ExpiresAt != nil {
		in, out := &in.ExpiresAt, &out.ExpiresAt
		*out = (*in).DeepCopy()
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new ActionApprovals.
func (in *ActionApprovals) DeepCopy() *ActionApprovals {
	if in == nil {
		return nil
	}
	out := new(ActionApprovals)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *ActionClassification) DeepCopyInto(out *ActionClassification) {
	*out = *in
	if in.Reasons != nil {
		in, out := &in.Reasons, &out.Reasons
		*out = make([]ClassificationReason, len(*in))
		copy(*out, *in)
	}
	if in.BlastRadius != nil {
		in, out := &in.BlastRadius, &out.BlastRadius
		*out = new(BlastRadius)
		**out = **in
	}
	if in.PolicySources != nil {
		in, out := &in.PolicySources, &out.PolicySources
		*out = make([]string, len(*in))
		copy(*out, *in)
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new ActionClassification.
func (in *ActionClassification) DeepCopy() *ActionClassification {
	if in == nil {
		return nil
	}
	out := new(ActionClassification)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *ActionRecord) DeepCopyInto(out *ActionRecord) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ObjectMeta.DeepCopyInto(&out.ObjectMeta)
	in.Spec.DeepCopyInto(&out.Spec)
	in.Status.DeepCopyInto(&out.Status)
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new ActionRecord.
func (in *ActionRecord) DeepCopy() *ActionRecord {
	if in == nil {
		return nil
	}
	out := new(ActionRecord)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *ActionRecord) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *ActionRecordList) DeepCopyInto(out *ActionRecordList) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ListMeta.DeepCopyInto(&out.ListMeta)
	if in.Items != nil {
		in, out := &in.Items, &out.Items
		*out = make([]ActionRecord, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new ActionRecordList.
func (in *ActionRecordList) DeepCopy() *ActionRecordList {
	if in == nil {
		return nil
	}
	out := new(ActionRecordList)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *ActionRecordList) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *ActionRecordSpec) DeepCopyInto(out *ActionRecordSpec) {
	*out = *in
	out.AgentRef = in.AgentRef
	out.Requester = in.Requester
	out.Trigger = in.Trigger
	if in.Trace != nil {
		in, out := &in.Trace, &out.Trace
		*out = new(ActionTrace)
		**out = **in
	}
	in.Classification.DeepCopyInto(&out.Classification)
	if in.Targets != nil {
		in, out := &in.Targets, &out.Targets
		*out = make([]TargetRef, len(*in))
		copy(*out, *in)
	}
	if in.PreState != nil {
		in, out := &in.PreState, &out.PreState
		*out = make([]PreStateSnapshot, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
	if in.Undo != nil {
		in, out := &in.Undo, &out.Undo
		*out = new(UndoPlan)
		(*in).DeepCopyInto(*out)
	}
	in.Retention.DeepCopyInto(&out.Retention)
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new ActionRecordSpec.
func (in *ActionRecordSpec) DeepCopy() *ActionRecordSpec {
	if in == nil {
		return nil
	}
	out := new(ActionRecordSpec)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *ActionRecordStatus) DeepCopyInto(out *ActionRecordStatus) {
	*out = *in
	if in.Applied != nil {
		in, out := &in.Applied, &out.Applied
		*out = make([]AppliedTarget, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
	if in.Verification != nil {
		in, out := &in.Verification, &out.Verification
		*out = new(ActionVerification)
		(*in).DeepCopyInto(*out)
	}
	if in.Recovery != nil {
		in, out := &in.Recovery, &out.Recovery
		*out = new(ActionRecovery)
		(*in).DeepCopyInto(*out)
	}
	if in.Report != nil {
		in, out := &in.Report, &out.Report
		*out = new(ActionReport)
		**out = **in
	}
	if in.Approvals != nil {
		in, out := &in.Approvals, &out.Approvals
		*out = new(ActionApprovals)
		(*in).DeepCopyInto(*out)
	}
	if in.Timestamps != nil {
		in, out := &in.Timestamps, &out.Timestamps
		*out = new(ActionTimestamps)
		(*in).DeepCopyInto(*out)
	}
	if in.Exported != nil {
		in, out := &in.Exported, &out.Exported
		*out = new(ExportStatus)
		(*in).DeepCopyInto(*out)
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new ActionRecordStatus.
func (in *ActionRecordStatus) DeepCopy() *ActionRecordStatus {
	if in == nil {
		return nil
	}
	out := new(ActionRecordStatus)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *ActionRecovery) DeepCopyInto(out *ActionRecovery) {
	*out = *in
	if in.Transitions != nil {
		in, out := &in.Transitions, &out.Transitions
		*out = make([]RecoveryTransition, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new ActionRecovery.
func (in *ActionRecovery) DeepCopy() *ActionRecovery {
	if in == nil {
		return nil
	}
	out := new(ActionRecovery)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *ActionReport) DeepCopyInto(out *ActionReport) {
	*out = *in
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new ActionReport.
func (in *ActionReport) DeepCopy() *ActionReport {
	if in == nil {
		return nil
	}
	out := new(ActionReport)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *ActionRequester) DeepCopyInto(out *ActionRequester) {
	*out = *in
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new ActionRequester.
func (in *ActionRequester) DeepCopy() *ActionRequester {
	if in == nil {
		return nil
	}
	out := new(ActionRequester)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *ActionTimestamps) DeepCopyInto(out *ActionTimestamps) {
	*out = *in
	if in.Submitted != nil {
		in, out := &in.Submitted, &out.Submitted
		*out = (*in).DeepCopy()
	}
	if in.Classified != nil {
		in, out := &in.Classified, &out.Classified
		*out = (*in).DeepCopy()
	}
	if in.Approved != nil {
		in, out := &in.Approved, &out.Approved
		*out = (*in).DeepCopy()
	}
	if in.ExecutionStarted != nil {
		in, out := &in.ExecutionStarted, &out.ExecutionStarted
		*out = (*in).DeepCopy()
	}
	if in.ExecutionEnded != nil {
		in, out := &in.ExecutionEnded, &out.ExecutionEnded
		*out = (*in).DeepCopy()
	}
	if in.Verified != nil {
		in, out := &in.Verified, &out.Verified
		*out = (*in).DeepCopy()
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new ActionTimestamps.
func (in *ActionTimestamps) DeepCopy() *ActionTimestamps {
	if in == nil {
		return nil
	}
	out := new(ActionTimestamps)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *ActionTrace) DeepCopyInto(out *ActionTrace) {
	*out = *in
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new ActionTrace.
func (in *ActionTrace) DeepCopy() *ActionTrace {
	if in == nil {
		return nil
	}
	out := new(ActionTrace)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *ActionTrigger) DeepCopyInto(out *ActionTrigger) {
	*out = *in
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new ActionTrigger.
func (in *ActionTrigger) DeepCopy() *ActionTrigger {
	if in == nil {
		return nil
	}
	out := new(ActionTrigger)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *ActionVerification) DeepCopyInto(out *ActionVerification) {
	*out = *in
	if in.CompletedAt != nil {
		in, out := &in.CompletedAt, &out.CompletedAt
		*out = (*in).DeepCopy()
	}
	if in.Checks != nil {
		in, out := &in.Checks, &out.Checks
		*out = make([]VerificationCheck, len(*in))
		copy(*out, *in)
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new ActionVerification.
func (in *ActionVerification) DeepCopy() *ActionVerification {
	if in == nil {
		return nil
	}
	out := new(ActionVerification)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *Agent) DeepCopyInto(out *Agent) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ObjectMeta.DeepCopyInto(&out.ObjectMeta)
	in.Spec.DeepCopyInto(&out.Spec)
	in.Status.DeepCopyInto(&out.Status)
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new Agent.
func (in *Agent) DeepCopy() *Agent {
	if in == nil {
		return nil
	}
	out := new(Agent)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *Agent) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *AgentIntegrationSpec) DeepCopyInto(out *AgentIntegrationSpec) {
	*out = *in
	in.IntegrationSpec.DeepCopyInto(&out.IntegrationSpec)
	if in.GoogleChat != nil {
		in, out := &in.GoogleChat, &out.GoogleChat
		*out = new(GoogleChatSpec)
		(*in).DeepCopyInto(*out)
	}
	if in.Slack != nil {
		in, out := &in.Slack, &out.Slack
		*out = new(SlackSpec)
		(*in).DeepCopyInto(*out)
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new AgentIntegrationSpec.
func (in *AgentIntegrationSpec) DeepCopy() *AgentIntegrationSpec {
	if in == nil {
		return nil
	}
	out := new(AgentIntegrationSpec)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *AgentList) DeepCopyInto(out *AgentList) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ListMeta.DeepCopyInto(&out.ListMeta)
	if in.Items != nil {
		in, out := &in.Items, &out.Items
		*out = make([]Agent, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new AgentList.
func (in *AgentList) DeepCopy() *AgentList {
	if in == nil {
		return nil
	}
	out := new(AgentList)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *AgentList) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *AgentObjectRef) DeepCopyInto(out *AgentObjectRef) {
	*out = *in
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new AgentObjectRef.
func (in *AgentObjectRef) DeepCopy() *AgentObjectRef {
	if in == nil {
		return nil
	}
	out := new(AgentObjectRef)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *AgentSpec) DeepCopyInto(out *AgentSpec) {
	*out = *in
	if in.Scope != nil {
		in, out := &in.Scope, &out.Scope
		*out = new(ScopeSpec)
		**out = **in
	}
	if in.ParentRef != nil {
		in, out := &in.ParentRef, &out.ParentRef
		*out = new(ParentRefSpec)
		**out = **in
	}
	if in.Operations != nil {
		in, out := &in.Operations, &out.Operations
		*out = new(OperationsSpec)
		(*in).DeepCopyInto(*out)
	}
	if in.IAC != nil {
		in, out := &in.IAC, &out.IAC
		*out = new(IACSpec)
		**out = **in
	}
	if in.Deployment != nil {
		in, out := &in.Deployment, &out.Deployment
		*out = new(DeploymentSpec)
		(*in).DeepCopyInto(*out)
	}
	if in.Security != nil {
		in, out := &in.Security, &out.Security
		*out = new(SecuritySpec)
		(*in).DeepCopyInto(*out)
	}
	if in.Harness != nil {
		in, out := &in.Harness, &out.Harness
		*out = new(HarnessSpec)
		(*in).DeepCopyInto(*out)
	}
	if in.Integration != nil {
		in, out := &in.Integration, &out.Integration
		*out = new(AgentIntegrationSpec)
		(*in).DeepCopyInto(*out)
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new AgentSpec.
func (in *AgentSpec) DeepCopy() *AgentSpec {
	if in == nil {
		return nil
	}
	out := new(AgentSpec)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *AgentStatus) DeepCopyInto(out *AgentStatus) {
	*out = *in
	if in.LastReconcileTime != nil {
		in, out := &in.LastReconcileTime, &out.LastReconcileTime
		*out = (*in).DeepCopy()
	}
	if in.Conditions != nil {
		in, out := &in.Conditions, &out.Conditions
		*out = make([]metav1.Condition, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
	out.DeploymentStatus = in.DeploymentStatus
	out.ServiceStatus = in.ServiceStatus
	out.StorageStatus = in.StorageStatus
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new AgentStatus.
func (in *AgentStatus) DeepCopy() *AgentStatus {
	if in == nil {
		return nil
	}
	out := new(AgentStatus)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *AppliedDiffOp) DeepCopyInto(out *AppliedDiffOp) {
	*out = *in
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new AppliedDiffOp.
func (in *AppliedDiffOp) DeepCopy() *AppliedDiffOp {
	if in == nil {
		return nil
	}
	out := new(AppliedDiffOp)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *AppliedTarget) DeepCopyInto(out *AppliedTarget) {
	*out = *in
	if in.Diff != nil {
		in, out := &in.Diff, &out.Diff
		*out = make([]AppliedDiffOp, len(*in))
		copy(*out, *in)
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new AppliedTarget.
func (in *AppliedTarget) DeepCopy() *AppliedTarget {
	if in == nil {
		return nil
	}
	out := new(AppliedTarget)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *ApprovalEntry) DeepCopyInto(out *ApprovalEntry) {
	*out = *in
	in.At.DeepCopyInto(&out.At)
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new ApprovalEntry.
func (in *ApprovalEntry) DeepCopy() *ApprovalEntry {
	if in == nil {
		return nil
	}
	out := new(ApprovalEntry)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *BlastRadius) DeepCopyInto(out *BlastRadius) {
	*out = *in
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new BlastRadius.
func (in *BlastRadius) DeepCopy() *BlastRadius {
	if in == nil {
		return nil
	}
	out := new(BlastRadius)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *BudgetClassSpec) DeepCopyInto(out *BudgetClassSpec) {
	*out = *in
	if in.RoutinePerHour != nil {
		in, out := &in.RoutinePerHour, &out.RoutinePerHour
		*out = new(int32)
		**out = **in
	}
	if in.ElevatedPerHour != nil {
		in, out := &in.ElevatedPerHour, &out.ElevatedPerHour
		*out = new(int32)
		**out = **in
	}
	if in.GatedPerHour != nil {
		in, out := &in.GatedPerHour, &out.GatedPerHour
		*out = new(int32)
		**out = **in
	}
	if in.ActionsPerDay != nil {
		in, out := &in.ActionsPerDay, &out.ActionsPerDay
		*out = new(int32)
		**out = **in
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new BudgetClassSpec.
func (in *BudgetClassSpec) DeepCopy() *BudgetClassSpec {
	if in == nil {
		return nil
	}
	out := new(BudgetClassSpec)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *ClassificationReason) DeepCopyInto(out *ClassificationReason) {
	*out = *in
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new ClassificationReason.
func (in *ClassificationReason) DeepCopy() *ClassificationReason {
	if in == nil {
		return nil
	}
	out := new(ClassificationReason)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *DeploymentSpec) DeepCopyInto(out *DeploymentSpec) {
	*out = *in
	if in.Tag != nil {
		in, out := &in.Tag, &out.Tag
		*out = new(string)
		**out = **in
	}
	if in.ImagePullPolicy != nil {
		in, out := &in.ImagePullPolicy, &out.ImagePullPolicy
		*out = new(v1.PullPolicy)
		**out = **in
	}
	if in.BrowserArgs != nil {
		in, out := &in.BrowserArgs, &out.BrowserArgs
		*out = make([]string, len(*in))
		copy(*out, *in)
	}
	if in.RuntimeClassName != nil {
		in, out := &in.RuntimeClassName, &out.RuntimeClassName
		*out = new(string)
		**out = **in
	}
	if in.Env != nil {
		in, out := &in.Env, &out.Env
		*out = make([]v1.EnvVar, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
	if in.InitContainers != nil {
		in, out := &in.InitContainers, &out.InitContainers
		*out = make([]v1.Container, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
	if in.Sidecars != nil {
		in, out := &in.Sidecars, &out.Sidecars
		*out = make([]v1.Container, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
	if in.SidecarVolumes != nil {
		in, out := &in.SidecarVolumes, &out.SidecarVolumes
		*out = make([]v1.Volume, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
	if in.ExtraVolumes != nil {
		in, out := &in.ExtraVolumes, &out.ExtraVolumes
		*out = make([]v1.Volume, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
	if in.ExtraVolumeMounts != nil {
		in, out := &in.ExtraVolumeMounts, &out.ExtraVolumeMounts
		*out = make([]v1.VolumeMount, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
	if in.PodAnnotations != nil {
		in, out := &in.PodAnnotations, &out.PodAnnotations
		*out = make(map[string]string, len(*in))
		for key, val := range *in {
			(*out)[key] = val
		}
	}
	if in.ScaleToZero != nil {
		in, out := &in.ScaleToZero, &out.ScaleToZero
		*out = new(bool)
		**out = **in
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new DeploymentSpec.
func (in *DeploymentSpec) DeepCopy() *DeploymentSpec {
	if in == nil {
		return nil
	}
	out := new(DeploymentSpec)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *DeploymentStatus) DeepCopyInto(out *DeploymentStatus) {
	*out = *in
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new DeploymentStatus.
func (in *DeploymentStatus) DeepCopy() *DeploymentStatus {
	if in == nil {
		return nil
	}
	out := new(DeploymentStatus)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *ExportStatus) DeepCopyInto(out *ExportStatus) {
	*out = *in
	if in.At != nil {
		in, out := &in.At, &out.At
		*out = (*in).DeepCopy()
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new ExportStatus.
func (in *ExportStatus) DeepCopy() *ExportStatus {
	if in == nil {
		return nil
	}
	out := new(ExportStatus)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *GitHubSpec) DeepCopyInto(out *GitHubSpec) {
	*out = *in
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new GitHubSpec.
func (in *GitHubSpec) DeepCopy() *GitHubSpec {
	if in == nil {
		return nil
	}
	out := new(GitHubSpec)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *GoogleChatSpec) DeepCopyInto(out *GoogleChatSpec) {
	*out = *in
	if in.Enabled != nil {
		in, out := &in.Enabled, &out.Enabled
		*out = new(bool)
		**out = **in
	}
	if in.AllowedUsers != nil {
		in, out := &in.AllowedUsers, &out.AllowedUsers
		*out = make([]string, len(*in))
		copy(*out, *in)
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new GoogleChatSpec.
func (in *GoogleChatSpec) DeepCopy() *GoogleChatSpec {
	if in == nil {
		return nil
	}
	out := new(GoogleChatSpec)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *HarnessSpec) DeepCopyInto(out *HarnessSpec) {
	*out = *in
	if in.Hermes != nil {
		in, out := &in.Hermes, &out.Hermes
		*out = new(HermesSpec)
		(*in).DeepCopyInto(*out)
	}
	if in.Memory != nil {
		in, out := &in.Memory, &out.Memory
		*out = new(MemorySpec)
		(*in).DeepCopyInto(*out)
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new HarnessSpec.
func (in *HarnessSpec) DeepCopy() *HarnessSpec {
	if in == nil {
		return nil
	}
	out := new(HarnessSpec)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *HermesSpec) DeepCopyInto(out *HermesSpec) {
	*out = *in
	if in.DashboardEnabled != nil {
		in, out := &in.DashboardEnabled, &out.DashboardEnabled
		*out = new(bool)
		**out = **in
	}
	if in.PluginsDebug != nil {
		in, out := &in.PluginsDebug, &out.PluginsDebug
		*out = new(bool)
		**out = **in
	}
	if in.ApiServerSecretRef != nil {
		in, out := &in.ApiServerSecretRef, &out.ApiServerSecretRef
		*out = new(v1.SecretKeySelector)
		(*in).DeepCopyInto(*out)
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new HermesSpec.
func (in *HermesSpec) DeepCopy() *HermesSpec {
	if in == nil {
		return nil
	}
	out := new(HermesSpec)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *IACSpec) DeepCopyInto(out *IACSpec) {
	*out = *in
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new IACSpec.
func (in *IACSpec) DeepCopy() *IACSpec {
	if in == nil {
		return nil
	}
	out := new(IACSpec)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *InitiativeBudgetSpec) DeepCopyInto(out *InitiativeBudgetSpec) {
	*out = *in
	if in.SelfInitiated != nil {
		in, out := &in.SelfInitiated, &out.SelfInitiated
		*out = new(BudgetClassSpec)
		(*in).DeepCopyInto(*out)
	}
	if in.HumanRequested != nil {
		in, out := &in.HumanRequested, &out.HumanRequested
		*out = new(BudgetClassSpec)
		(*in).DeepCopyInto(*out)
	}
	if in.MaxObjectsPerAction != nil {
		in, out := &in.MaxObjectsPerAction, &out.MaxObjectsPerAction
		*out = new(int32)
		**out = **in
	}
	if in.FlapWindow != nil {
		in, out := &in.FlapWindow, &out.FlapWindow
		*out = new(metav1.Duration)
		**out = **in
	}
	if in.FlapThreshold != nil {
		in, out := &in.FlapThreshold, &out.FlapThreshold
		*out = new(int32)
		**out = **in
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new InitiativeBudgetSpec.
func (in *InitiativeBudgetSpec) DeepCopy() *InitiativeBudgetSpec {
	if in == nil {
		return nil
	}
	out := new(InitiativeBudgetSpec)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *IntegrationSpec) DeepCopyInto(out *IntegrationSpec) {
	*out = *in
	if in.GitHub != nil {
		in, out := &in.GitHub, &out.GitHub
		*out = new(GitHubSpec)
		**out = **in
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new IntegrationSpec.
func (in *IntegrationSpec) DeepCopy() *IntegrationSpec {
	if in == nil {
		return nil
	}
	out := new(IntegrationSpec)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *MemorySpec) DeepCopyInto(out *MemorySpec) {
	*out = *in
	if in.MemoryEnabled != nil {
		in, out := &in.MemoryEnabled, &out.MemoryEnabled
		*out = new(bool)
		**out = **in
	}
	if in.UserProfileEnabled != nil {
		in, out := &in.UserProfileEnabled, &out.UserProfileEnabled
		*out = new(bool)
		**out = **in
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new MemorySpec.
func (in *MemorySpec) DeepCopy() *MemorySpec {
	if in == nil {
		return nil
	}
	out := new(MemorySpec)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *ObjectStoreRef) DeepCopyInto(out *ObjectStoreRef) {
	*out = *in
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new ObjectStoreRef.
func (in *ObjectStoreRef) DeepCopy() *ObjectStoreRef {
	if in == nil {
		return nil
	}
	out := new(ObjectStoreRef)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *OperationsSpec) DeepCopyInto(out *OperationsSpec) {
	*out = *in
	if in.Paused != nil {
		in, out := &in.Paused, &out.Paused
		*out = new(bool)
		**out = **in
	}
	if in.InitiativeBudget != nil {
		in, out := &in.InitiativeBudget, &out.InitiativeBudget
		*out = new(InitiativeBudgetSpec)
		(*in).DeepCopyInto(*out)
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new OperationsSpec.
func (in *OperationsSpec) DeepCopy() *OperationsSpec {
	if in == nil {
		return nil
	}
	out := new(OperationsSpec)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *ParentRefSpec) DeepCopyInto(out *ParentRefSpec) {
	*out = *in
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new ParentRefSpec.
func (in *ParentRefSpec) DeepCopy() *ParentRefSpec {
	if in == nil {
		return nil
	}
	out := new(ParentRefSpec)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *PreStateSnapshot) DeepCopyInto(out *PreStateSnapshot) {
	*out = *in
	in.CapturedAt.DeepCopyInto(&out.CapturedAt)
	if in.Object != nil {
		in, out := &in.Object, &out.Object
		*out = new(runtime.RawExtension)
		(*in).DeepCopyInto(*out)
	}
	if in.ObjectRef != nil {
		in, out := &in.ObjectRef, &out.ObjectRef
		*out = new(ObjectStoreRef)
		**out = **in
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new PreStateSnapshot.
func (in *PreStateSnapshot) DeepCopy() *PreStateSnapshot {
	if in == nil {
		return nil
	}
	out := new(PreStateSnapshot)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *RecoveryTransition) DeepCopyInto(out *RecoveryTransition) {
	*out = *in
	in.At.DeepCopyInto(&out.At)
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new RecoveryTransition.
func (in *RecoveryTransition) DeepCopy() *RecoveryTransition {
	if in == nil {
		return nil
	}
	out := new(RecoveryTransition)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *RetentionSpec) DeepCopyInto(out *RetentionSpec) {
	*out = *in
	in.ExpiresAt.DeepCopyInto(&out.ExpiresAt)
	in.UndoWindowExpiresAt.DeepCopyInto(&out.UndoWindowExpiresAt)
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new RetentionSpec.
func (in *RetentionSpec) DeepCopy() *RetentionSpec {
	if in == nil {
		return nil
	}
	out := new(RetentionSpec)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *ScopeSpec) DeepCopyInto(out *ScopeSpec) {
	*out = *in
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new ScopeSpec.
func (in *ScopeSpec) DeepCopy() *ScopeSpec {
	if in == nil {
		return nil
	}
	out := new(ScopeSpec)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *SecuritySpec) DeepCopyInto(out *SecuritySpec) {
	*out = *in
	if in.ServiceAccountAnnotations != nil {
		in, out := &in.ServiceAccountAnnotations, &out.ServiceAccountAnnotations
		*out = make(map[string]string, len(*in))
		for key, val := range *in {
			(*out)[key] = val
		}
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new SecuritySpec.
func (in *SecuritySpec) DeepCopy() *SecuritySpec {
	if in == nil {
		return nil
	}
	out := new(SecuritySpec)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *ServiceStatus) DeepCopyInto(out *ServiceStatus) {
	*out = *in
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new ServiceStatus.
func (in *ServiceStatus) DeepCopy() *ServiceStatus {
	if in == nil {
		return nil
	}
	out := new(ServiceStatus)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *SlackSpec) DeepCopyInto(out *SlackSpec) {
	*out = *in
	if in.Enabled != nil {
		in, out := &in.Enabled, &out.Enabled
		*out = new(bool)
		**out = **in
	}
	if in.BotTokenSecretRef != nil {
		in, out := &in.BotTokenSecretRef, &out.BotTokenSecretRef
		*out = new(v1.SecretKeySelector)
		(*in).DeepCopyInto(*out)
	}
	if in.AppTokenSecretRef != nil {
		in, out := &in.AppTokenSecretRef, &out.AppTokenSecretRef
		*out = new(v1.SecretKeySelector)
		(*in).DeepCopyInto(*out)
	}
	if in.AllowedUsers != nil {
		in, out := &in.AllowedUsers, &out.AllowedUsers
		*out = make([]string, len(*in))
		copy(*out, *in)
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new SlackSpec.
func (in *SlackSpec) DeepCopy() *SlackSpec {
	if in == nil {
		return nil
	}
	out := new(SlackSpec)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *StorageStatus) DeepCopyInto(out *StorageStatus) {
	*out = *in
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new StorageStatus.
func (in *StorageStatus) DeepCopy() *StorageStatus {
	if in == nil {
		return nil
	}
	out := new(StorageStatus)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *TargetRef) DeepCopyInto(out *TargetRef) {
	*out = *in
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new TargetRef.
func (in *TargetRef) DeepCopy() *TargetRef {
	if in == nil {
		return nil
	}
	out := new(TargetRef)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *UndoPlan) DeepCopyInto(out *UndoPlan) {
	*out = *in
	in.GeneratedAt.DeepCopyInto(&out.GeneratedAt)
	if in.Steps != nil {
		in, out := &in.Steps, &out.Steps
		*out = make([]UndoStep, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
	if in.Caveats != nil {
		in, out := &in.Caveats, &out.Caveats
		*out = make([]string, len(*in))
		copy(*out, *in)
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new UndoPlan.
func (in *UndoPlan) DeepCopy() *UndoPlan {
	if in == nil {
		return nil
	}
	out := new(UndoPlan)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *UndoPrecondition) DeepCopyInto(out *UndoPrecondition) {
	*out = *in
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new UndoPrecondition.
func (in *UndoPrecondition) DeepCopy() *UndoPrecondition {
	if in == nil {
		return nil
	}
	out := new(UndoPrecondition)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *UndoStep) DeepCopyInto(out *UndoStep) {
	*out = *in
	out.Target = in.Target
	if in.Object != nil {
		in, out := &in.Object, &out.Object
		*out = new(runtime.RawExtension)
		(*in).DeepCopyInto(*out)
	}
	if in.ObjectRef != nil {
		in, out := &in.ObjectRef, &out.ObjectRef
		*out = new(ObjectStoreRef)
		**out = **in
	}
	if in.Preconditions != nil {
		in, out := &in.Preconditions, &out.Preconditions
		*out = new(UndoPrecondition)
		**out = **in
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new UndoStep.
func (in *UndoStep) DeepCopy() *UndoStep {
	if in == nil {
		return nil
	}
	out := new(UndoStep)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *VerificationCheck) DeepCopyInto(out *VerificationCheck) {
	*out = *in
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new VerificationCheck.
func (in *VerificationCheck) DeepCopy() *VerificationCheck {
	if in == nil {
		return nil
	}
	out := new(VerificationCheck)
	in.DeepCopyInto(out)
	return out
}
