//go:build !ignore_autogenerated

/*
Copyright 2026.

Licensed under the Apache License, Version 2.0 (the "License");
you may not use this file except in compliance with the License.
You may obtain a copy of the License at

    http://www.apache.org/licenses/LICENSE-2.0

Unless required by applicable law or agreed to in writing, software
distributed under the License is distributed on an "AS IS" BASIS,
WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
See the License for the specific language governing permissions and
limitations under the License.
*/

// Code generated by controller-gen. DO NOT EDIT.

package v1alpha1

import (
	"k8s.io/api/core/v1"
	metav1 "k8s.io/apimachinery/pkg/apis/meta/v1"
	"k8s.io/apimachinery/pkg/runtime"
)

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *ActionApprovals) DeepCopyInto(out *ActionApprovals) {
	*out = *in
	if in.Granted != nil {
		in, out := &in.Granted, &out.Granted
		*out = make([]ApprovalEntry, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
	if in.Rejected != nil {
		in, out := &in.Rejected, &out.Rejected
		*out = make([]ApprovalEntry, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
	if in.ExpiresAt != nil {
		in, out := &in.ExpiresAt, &out.ExpiresAt
		*out = (*in).DeepCopy()
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new ActionApprovals.
func (in *ActionApprovals) DeepCopy() *ActionApprovals {
	if in == nil {
		return nil
	}
	out := new(ActionApprovals)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *ActionClassification) DeepCopyInto(out *ActionClassification) {
	*out = *in
	if in.Reasons != nil {
		in, out := &in.Reasons, &out.Reasons
		*out = make([]ClassificationReason, len(*in))
		copy(*out, *in)
	}
	if in.BlastRadius != nil {
		in, out := &in.BlastRadius, &out.BlastRadius
		*out = new(BlastRadius)
		**out = **in
	}
	if in.PolicySources != nil {
		in, out := &in.PolicySources, &out.PolicySources
		*out = make([]string, len(*in))
		copy(*out, *in)
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new ActionClassification.
func (in *ActionClassification) DeepCopy() *ActionClassification {
	if in == nil {
		return nil
	}
	out := new(ActionClassification)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *ActionRecord) DeepCopyInto(out *ActionRecord) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ObjectMeta.DeepCopyInto(&out.ObjectMeta)
	in.Spec.DeepCopyInto(&out.Spec)
	in.Status.DeepCopyInto(&out.Status)
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new ActionRecord.
func (in *ActionRecord) DeepCopy() *ActionRecord {
	if in == nil {
		return nil
	}
	out := new(ActionRecord)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *ActionRecord) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *ActionRecordList) DeepCopyInto(out *ActionRecordList) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ListMeta.DeepCopyInto(&out.ListMeta)
	if in.Items != nil {
		in, out := &in.Items, &out.Items
		*out = make([]ActionRecord, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new ActionRecordList.
func (in *ActionRecordList) DeepCopy() *ActionRecordList {
	if in == nil {
		return nil
	}
	out := new(ActionRecordList)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *ActionRecordList) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *ActionRecordSpec) DeepCopyInto(out *ActionRecordSpec) {
	*out = *in
	out.AgentRef = in.AgentRef
	out.Requester = in.Requester
	out.Trigger = in.Trigger
	if in.Trace != nil {
		in, out := &in.Trace, &out.Trace
		*out = new(ActionTrace)
		**out = **in
	}
	in.Classification.DeepCopyInto(&out.Classification)
	if in.Targets != nil {
		in, out := &in.Targets, &out.Targets
		*out = make([]TargetRef, len(*in))
		copy(*out, *in)
	}
	if in.PreState != nil {
		in, out := &in.PreState, &out.PreState
		*out = make([]PreStateSnapshot, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
	if in.Undo != nil {
		in, out := &in.Undo, &out.Undo
		*out = new(UndoPlan)
		(*in).DeepCopyInto(*out)
	}
	in.Retention.DeepCopyInto(&out.Retention)
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new ActionRecordSpec.
func (in *ActionRecordSpec) DeepCopy() *ActionRecordSpec {
	if in == nil {
		return nil
	}
	out := new(ActionRecordSpec)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *ActionRecordStatus) DeepCopyInto(out *ActionRecordStatus) {
	*out = *in
	if in.Applied != nil {
		in, out := &in.Applied, &out.Applied
		*out = make([]AppliedTarget, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
	if in.Verification != nil {
		in, out := &in.Verification, &out.Verification
		*out = new(ActionVerification)
		(*in).DeepCopyInto(*out)
	}
	if in.Recovery != nil {
		in, out := &in.Recovery, &out.Recovery
		*out = new(ActionRecovery)
		(*in).DeepCopyInto(*out)
	}
	if in.Report != nil {
		in, out := &in.Report, &out.Report
		*out = new(ActionReport)
		**out = **in
	}
	if in.Approvals != nil {
		in, out := &in.Approvals, &out.Approvals
		*out = new(ActionApprovals)
		(*in).DeepCopyInto(*out)
	}
	if in.Timestamps != nil {
		in, out := &in.Timestamps, &out.Timestamps
		*out = new(ActionTimestamps)
		(*in).DeepCopyInto(*out)
	}
	if in.Exported != nil {
		in, out := &in.Exported, &out.Exported
		*out = new(ExportStatus)
		(*in).DeepCopyInto(*out)
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new ActionRecordStatus.
func (in *ActionRecordStatus) DeepCopy() *ActionRecordStatus {
	if in == nil {
		return nil
	}
	out := new(ActionRecordStatus)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *ActionRecovery) DeepCopyInto(out *ActionRecovery) {
	*out = *in
	if in.Transitions != nil {
		in, out := &in.Transitions, &out.Transitions
		*out = make([]RecoveryTransition, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new ActionRecovery.
func (in *ActionRecovery) DeepCopy() *ActionRecovery {
	if in == nil {
		return nil
	}
	out := new(ActionRecovery)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *ActionRef) DeepCopyInto(out *ActionRef) {
	*out = *in
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new ActionRef.
func (in *ActionRef) DeepCopy() *ActionRef {
	if in == nil {
		return nil
	}
	out := new(ActionRef)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *ActionReport) DeepCopyInto(out *ActionReport) {
	*out = *in
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new ActionReport.
func (in *ActionReport) DeepCopy() *ActionReport {
	if in == nil {
		return nil
	}
	out := new(ActionReport)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *ActionRequester) DeepCopyInto(out *ActionRequester) {
	*out = *in
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new ActionRequester.
func (in *ActionRequester) DeepCopy() *ActionRequester {
	if in == nil {
		return nil
	}
	out := new(ActionRequester)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *ActionTimestamps) DeepCopyInto(out *ActionTimestamps) {
	*out = *in
	if in.Submitted != nil {
		in, out := &in.Submitted, &out.Submitted
		*out = (*in).DeepCopy()
	}
	if in.Classified != nil {
		in, out := &in.Classified, &out.Classified
		*out = (*in).DeepCopy()
	}
	if in.Approved != nil {
		in, out := &in.Approved, &out.Approved
		*out = (*in).DeepCopy()
	}
	if in.ExecutionStarted != nil {
		in, out := &in.ExecutionStarted, &out.ExecutionStarted
		*out = (*in).DeepCopy()
	}
	if in.ExecutionEnded != nil {
		in, out := &in.ExecutionEnded, &out.ExecutionEnded
		*out = (*in).DeepCopy()
	}
	if in.Verified != nil {
		in, out := &in.Verified, &out.Verified
		*out = (*in).DeepCopy()
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new ActionTimestamps.
func (in *ActionTimestamps) DeepCopy() *ActionTimestamps {
	if in == nil {
		return nil
	}
	out := new(ActionTimestamps)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *ActionTrace) DeepCopyInto(out *ActionTrace) {
	*out = *in
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new ActionTrace.
func (in *ActionTrace) DeepCopy() *ActionTrace {
	if in == nil {
		return nil
	}
	out := new(ActionTrace)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *ActionTrigger) DeepCopyInto(out *ActionTrigger) {
	*out = *in
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new ActionTrigger.
func (in *ActionTrigger) DeepCopy() *ActionTrigger {
	if in == nil {
		return nil
	}
	out := new(ActionTrigger)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *ActionVerification) DeepCopyInto(out *ActionVerification) {
	*out = *in
	if in.CompletedAt != nil {
		in, out := &in.CompletedAt, &out.CompletedAt
		*out = (*in).DeepCopy()
	}
	if in.Checks != nil {
		in, out := &in.Checks, &out.Checks
		*out = make([]VerificationCheck, len(*in))
		copy(*out, *in)
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new ActionVerification.
func (in *ActionVerification) DeepCopy() *ActionVerification {
	if in == nil {
		return nil
	}
	out := new(ActionVerification)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *Agent) DeepCopyInto(out *Agent) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ObjectMeta.DeepCopyInto(&out.ObjectMeta)
	in.Spec.DeepCopyInto(&out.Spec)
	in.Status.DeepCopyInto(&out.Status)
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new Agent.
func (in *Agent) DeepCopy() *Agent {
	if in == nil {
		return nil
	}
	out := new(Agent)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *Agent) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *AgentIntegrationSpec) DeepCopyInto(out *AgentIntegrationSpec) {
	*out = *in
	in.IntegrationSpec.DeepCopyInto(&out.IntegrationSpec)
	if in.GoogleChat != nil {
		in, out := &in.GoogleChat, &out.GoogleChat
		*out = new(GoogleChatSpec)
		(*in).DeepCopyInto(*out)
	}
	if in.Slack != nil {
		in, out := &in.Slack, &out.Slack
		*out = new(SlackSpec)
		(*in).DeepCopyInto(*out)
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new AgentIntegrationSpec.
func (in *AgentIntegrationSpec) DeepCopy() *AgentIntegrationSpec {
	if in == nil {
		return nil
	}
	out := new(AgentIntegrationSpec)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *AgentList) DeepCopyInto(out *AgentList) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ListMeta.DeepCopyInto(&out.ListMeta)
	if in.Items != nil {
		in, out := &in.Items, &out.Items
		*out = make([]Agent, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new AgentList.
func (in *AgentList) DeepCopy() *AgentList {
	if in == nil {
		return nil
	}
	out := new(AgentList)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *AgentList) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *AgentObjectRef) DeepCopyInto(out *AgentObjectRef) {
	*out = *in
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new AgentObjectRef.
func (in *AgentObjectRef) DeepCopy() *AgentObjectRef {
	if in == nil {
		return nil
	}
	out := new(AgentObjectRef)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *AgentSpec) DeepCopyInto(out *AgentSpec) {
	*out = *in
	if in.Scope != nil {
		in, out := &in.Scope, &out.Scope
		*out = new(ScopeSpec)
		**out = **in
	}
	if in.ParentRef != nil {
		in, out := &in.ParentRef, &out.ParentRef
		*out = new(ParentRefSpec)
		**out = **in
	}
	if in.Operations != nil {
		in, out := &in.Operations, &out.Operations
		*out = new(OperationsSpec)
		(*in).DeepCopyInto(*out)
	}
	if in.IAC != nil {
		in, out := &in.IAC, &out.IAC
		*out = new(IACSpec)
		**out = **in
	}
	if in.Deployment != nil {
		in, out := &in.Deployment, &out.Deployment
		*out = new(DeploymentSpec)
		(*in).DeepCopyInto(*out)
	}
	if in.Security != nil {
		in, out := &in.Security, &out.Security
		*out = new(SecuritySpec)
		(*in).DeepCopyInto(*out)
	}
	if in.Harness != nil {
		in, out := &in.Harness, &out.Harness
		*out = new(HarnessSpec)
		(*in).DeepCopyInto(*out)
	}
	if in.Integration != nil {
		in, out := &in.Integration, &out.Integration
		*out = new(AgentIntegrationSpec)
		(*in).DeepCopyInto(*out)
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new AgentSpec.
func (in *AgentSpec) DeepCopy() *AgentSpec {
	if in == nil {
		return nil
	}
	out := new(AgentSpec)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *AgentStatus) DeepCopyInto(out *AgentStatus) {
	*out = *in
	if in.LastReconcileTime != nil {
		in, out := &in.LastReconcileTime, &out.LastReconcileTime
		*out = (*in).DeepCopy()
	}
	if in.Conditions != nil {
		in, out := &in.Conditions, &out.Conditions
		*out = make([]metav1.Condition, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
	out.DeploymentStatus = in.DeploymentStatus
	out.ServiceStatus = in.ServiceStatus
	out.StorageStatus = in.StorageStatus
	if in.Operations != nil {
		in, out := &in.Operations, &out.Operations
		*out = new(OperationsStatus)
		(*in).DeepCopyInto(*out)
	}
	if in.Broker != nil {
		in, out := &in.Broker, &out.Broker
		*out = new(BrokerStatus)
		**out = **in
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new AgentStatus.
func (in *AgentStatus) DeepCopy() *AgentStatus {
	if in == nil {
		return nil
	}
	out := new(AgentStatus)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *AppliedDiffOp) DeepCopyInto(out *AppliedDiffOp) {
	*out = *in
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new AppliedDiffOp.
func (in *AppliedDiffOp) DeepCopy() *AppliedDiffOp {
	if in == nil {
		return nil
	}
	out := new(AppliedDiffOp)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *AppliedTarget) DeepCopyInto(out *AppliedTarget) {
	*out = *in
	if in.Diff != nil {
		in, out := &in.Diff, &out.Diff
		*out = make([]AppliedDiffOp, len(*in))
		copy(*out, *in)
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new AppliedTarget.
func (in *AppliedTarget) DeepCopy() *AppliedTarget {
	if in == nil {
		return nil
	}
	out := new(AppliedTarget)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *ApprovalEntry) DeepCopyInto(out *ApprovalEntry) {
	*out = *in
	in.At.DeepCopyInto(&out.At)
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new ApprovalEntry.
func (in *ApprovalEntry) DeepCopy() *ApprovalEntry {
	if in == nil {
		return nil
	}
	out := new(ApprovalEntry)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *ApprovalNotify) DeepCopyInto(out *ApprovalNotify) {
	*out = *in
	if in.Slack != nil {
		in, out := &in.Slack, &out.Slack
		*out = new(SlackNotify)
		**out = **in
	}
	if in.GoogleChat != nil {
		in, out := &in.GoogleChat, &out.GoogleChat
		*out = new(GoogleChatNotify)
		**out = **in
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new ApprovalNotify.
func (in *ApprovalNotify) DeepCopy() *ApprovalNotify {
	if in == nil {
		return nil
	}
	out := new(ApprovalNotify)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *ApprovalRoster) DeepCopyInto(out *ApprovalRoster) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ObjectMeta.DeepCopyInto(&out.ObjectMeta)
	in.Spec.DeepCopyInto(&out.Spec)
	in.Status.DeepCopyInto(&out.Status)
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new ApprovalRoster.
func (in *ApprovalRoster) DeepCopy() *ApprovalRoster {
	if in == nil {
		return nil
	}
	out := new(ApprovalRoster)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *ApprovalRoster) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *ApprovalRosterList) DeepCopyInto(out *ApprovalRosterList) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ListMeta.DeepCopyInto(&out.ListMeta)
	if in.Items != nil {
		in, out := &in.Items, &out.Items
		*out = make([]ApprovalRoster, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new ApprovalRosterList.
func (in *ApprovalRosterList) DeepCopy() *ApprovalRosterList {
	if in == nil {
		return nil
	}
	out := new(ApprovalRosterList)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *ApprovalRosterList) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *ApprovalRosterSpec) DeepCopyInto(out *ApprovalRosterSpec) {
	*out = *in
	if in.Approvers != nil {
		in, out := &in.Approvers, &out.Approvers
		*out = make([]Approver, len(*in))
		copy(*out, *in)
	}
	if in.MinApprovals != nil {
		in, out := &in.MinApprovals, &out.MinApprovals
		*out = new(int32)
		**out = **in
	}
	if in.AllowSelfApproval != nil {
		in, out := &in.AllowSelfApproval, &out.AllowSelfApproval
		*out = new(bool)
		**out = **in
	}
	if in.TTL != nil {
		in, out := &in.TTL, &out.TTL
		*out = new(metav1.Duration)
		**out = **in
	}
	if in.Notify != nil {
		in, out := &in.Notify, &out.Notify
		*out = new(ApprovalNotify)
		(*in).DeepCopyInto(*out)
	}
	if in.EscalateTo != nil {
		in, out := &in.EscalateTo, &out.EscalateTo
		*out = new(RosterRef)
		**out = **in
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new ApprovalRosterSpec.
func (in *ApprovalRosterSpec) DeepCopy() *ApprovalRosterSpec {
	if in == nil {
		return nil
	}
	out := new(ApprovalRosterSpec)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *ApprovalRosterStatus) DeepCopyInto(out *ApprovalRosterStatus) {
	*out = *in
	if in.Conditions != nil {
		in, out := &in.Conditions, &out.Conditions
		*out = make([]metav1.Condition, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new ApprovalRosterStatus.
func (in *ApprovalRosterStatus) DeepCopy() *ApprovalRosterStatus {
	if in == nil {
		return nil
	}
	out := new(ApprovalRosterStatus)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *Approver) DeepCopyInto(out *Approver) {
	*out = *in
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new Approver.
func (in *Approver) DeepCopy() *Approver {
	if in == nil {
		return nil
	}
	out := new(Approver)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *BlastRadius) DeepCopyInto(out *BlastRadius) {
	*out = *in
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new BlastRadius.
func (in *BlastRadius) DeepCopy() *BlastRadius {
	if in == nil {
		return nil
	}
	out := new(BlastRadius)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *BrokerStatus) DeepCopyInto(out *BrokerStatus) {
	*out = *in
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new BrokerStatus.
func (in *BrokerStatus) DeepCopy() *BrokerStatus {
	if in == nil {
		return nil
	}
	out := new(BrokerStatus)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *BudgetClassSpec) DeepCopyInto(out *BudgetClassSpec) {
	*out = *in
	if in.RoutinePerHour != nil {
		in, out := &in.RoutinePerHour, &out.RoutinePerHour
		*out = new(int32)
		**out = **in
	}
	if in.ElevatedPerHour != nil {
		in, out := &in.ElevatedPerHour, &out.ElevatedPerHour
		*out = new(int32)
		**out = **in
	}
	if in.GatedPerHour != nil {
		in, out := &in.GatedPerHour, &out.GatedPerHour
		*out = new(int32)
		**out = **in
	}
	if in.ActionsPerDay != nil {
		in, out := &in.ActionsPerDay, &out.ActionsPerDay
		*out = new(int32)
		**out = **in
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new BudgetClassSpec.
func (in *BudgetClassSpec) DeepCopy() *BudgetClassSpec {
	if in == nil {
		return nil
	}
	out := new(BudgetClassSpec)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *ChangePolicy) DeepCopyInto(out *ChangePolicy) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ObjectMeta.DeepCopyInto(&out.ObjectMeta)
	in.Spec.DeepCopyInto(&out.Spec)
	in.Status.DeepCopyInto(&out.Status)
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new ChangePolicy.
func (in *ChangePolicy) DeepCopy() *ChangePolicy {
	if in == nil {
		return nil
	}
	out := new(ChangePolicy)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *ChangePolicy) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *ChangePolicyAgentSelector) DeepCopyInto(out *ChangePolicyAgentSelector) {
	*out = *in
	if in.Tiers != nil {
		in, out := &in.Tiers, &out.Tiers
		*out = make([]AgentTier, len(*in))
		copy(*out, *in)
	}
	if in.Scopes != nil {
		in, out := &in.Scopes, &out.Scopes
		*out = make([]ScopeSpec, len(*in))
		copy(*out, *in)
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new ChangePolicyAgentSelector.
func (in *ChangePolicyAgentSelector) DeepCopy() *ChangePolicyAgentSelector {
	if in == nil {
		return nil
	}
	out := new(ChangePolicyAgentSelector)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *ChangePolicyList) DeepCopyInto(out *ChangePolicyList) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ListMeta.DeepCopyInto(&out.ListMeta)
	if in.Items != nil {
		in, out := &in.Items, &out.Items
		*out = make([]ChangePolicy, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new ChangePolicyList.
func (in *ChangePolicyList) DeepCopy() *ChangePolicyList {
	if in == nil {
		return nil
	}
	out := new(ChangePolicyList)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *ChangePolicyList) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *ChangePolicySpec) DeepCopyInto(out *ChangePolicySpec) {
	*out = *in
	if in.AgentSelector != nil {
		in, out := &in.AgentSelector, &out.AgentSelector
		*out = new(ChangePolicyAgentSelector)
		(*in).DeepCopyInto(*out)
	}
	if in.Rules != nil {
		in, out := &in.Rules, &out.Rules
		*out = make([]ChangeRule, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new ChangePolicySpec.
func (in *ChangePolicySpec) DeepCopy() *ChangePolicySpec {
	if in == nil {
		return nil
	}
	out := new(ChangePolicySpec)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *ChangePolicyStatus) DeepCopyInto(out *ChangePolicyStatus) {
	*out = *in
	if in.Conditions != nil {
		in, out := &in.Conditions, &out.Conditions
		*out = make([]metav1.Condition, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new ChangePolicyStatus.
func (in *ChangePolicyStatus) DeepCopy() *ChangePolicyStatus {
	if in == nil {
		return nil
	}
	out := new(ChangePolicyStatus)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *ChangeRule) DeepCopyInto(out *ChangeRule) {
	*out = *in
	in.When.DeepCopyInto(&out.When)
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new ChangeRule.
func (in *ChangeRule) DeepCopy() *ChangeRule {
	if in == nil {
		return nil
	}
	out := new(ChangeRule)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *ChangeRuleWhen) DeepCopyInto(out *ChangeRuleWhen) {
	*out = *in
	if in.Verbs != nil {
		in, out := &in.Verbs, &out.Verbs
		*out = make([]ChangeVerb, len(*in))
		copy(*out, *in)
	}
	if in.Kinds != nil {
		in, out := &in.Kinds, &out.Kinds
		*out = make([]KindRefSpec, len(*in))
		copy(*out, *in)
	}
	if in.ExcludeKinds != nil {
		in, out := &in.ExcludeKinds, &out.ExcludeKinds
		*out = make([]KindRefSpec, len(*in))
		copy(*out, *in)
	}
	if in.Namespaces != nil {
		in, out := &in.Namespaces, &out.Namespaces
		*out = make([]string, len(*in))
		copy(*out, *in)
	}
	if in.NamespaceSelector != nil {
		in, out := &in.NamespaceSelector, &out.NamespaceSelector
		*out = new(metav1.LabelSelector)
		(*in).DeepCopyInto(*out)
	}
	if in.LabelSelector != nil {
		in, out := &in.LabelSelector, &out.LabelSelector
		*out = new(metav1.LabelSelector)
		(*in).DeepCopyInto(*out)
	}
	if in.FieldPaths != nil {
		in, out := &in.FieldPaths, &out.FieldPaths
		*out = make([]string, len(*in))
		copy(*out, *in)
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new ChangeRuleWhen.
func (in *ChangeRuleWhen) DeepCopy() *ChangeRuleWhen {
	if in == nil {
		return nil
	}
	out := new(ChangeRuleWhen)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *ClassificationReason) DeepCopyInto(out *ClassificationReason) {
	*out = *in
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new ClassificationReason.
func (in *ClassificationReason) DeepCopy() *ClassificationReason {
	if in == nil {
		return nil
	}
	out := new(ClassificationReason)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *DeploymentSpec) DeepCopyInto(out *DeploymentSpec) {
	*out = *in
	if in.Tag != nil {
		in, out := &in.Tag, &out.Tag
		*out = new(string)
		**out = **in
	}
	if in.ImagePullPolicy != nil {
		in, out := &in.ImagePullPolicy, &out.ImagePullPolicy
		*out = new(v1.PullPolicy)
		**out = **in
	}
	if in.BrowserArgs != nil {
		in, out := &in.BrowserArgs, &out.BrowserArgs
		*out = make([]string, len(*in))
		copy(*out, *in)
	}
	if in.RuntimeClassName != nil {
		in, out := &in.RuntimeClassName, &out.RuntimeClassName
		*out = new(string)
		**out = **in
	}
	if in.Env != nil {
		in, out := &in.Env, &out.Env
		*out = make([]v1.EnvVar, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
	if in.InitContainers != nil {
		in, out := &in.InitContainers, &out.InitContainers
		*out = make([]v1.Container, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
	if in.Sidecars != nil {
		in, out := &in.Sidecars, &out.Sidecars
		*out = make([]v1.Container, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
	if in.SidecarVolumes != nil {
		in, out := &in.SidecarVolumes, &out.SidecarVolumes
		*out = make([]v1.Volume, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
	if in.ExtraVolumes != nil {
		in, out := &in.ExtraVolumes, &out.ExtraVolumes
		*out = make([]v1.Volume, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
	if in.ExtraVolumeMounts != nil {
		in, out := &in.ExtraVolumeMounts, &out.ExtraVolumeMounts
		*out = make([]v1.VolumeMount, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
	if in.PodAnnotations != nil {
		in, out := &in.PodAnnotations, &out.PodAnnotations
		*out = make(map[string]string, len(*in))
		for key, val := range *in {
			(*out)[key] = val
		}
	}
	if in.ScaleToZero != nil {
		in, out := &in.ScaleToZero, &out.ScaleToZero
		*out = new(bool)
		**out = **in
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new DeploymentSpec.
func (in *DeploymentSpec) DeepCopy() *DeploymentSpec {
	if in == nil {
		return nil
	}
	out := new(DeploymentSpec)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *DeploymentStatus) DeepCopyInto(out *DeploymentStatus) {
	*out = *in
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new DeploymentStatus.
func (in *DeploymentStatus) DeepCopy() *DeploymentStatus {
	if in == nil {
		return nil
	}
	out := new(DeploymentStatus)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *ExportStatus) DeepCopyInto(out *ExportStatus) {
	*out = *in
	if in.At != nil {
		in, out := &in.At, &out.At
		*out = (*in).DeepCopy()
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new ExportStatus.
func (in *ExportStatus) DeepCopy() *ExportStatus {
	if in == nil {
		return nil
	}
	out := new(ExportStatus)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *FleetFreeze) DeepCopyInto(out *FleetFreeze) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ObjectMeta.DeepCopyInto(&out.ObjectMeta)
	in.Spec.DeepCopyInto(&out.Spec)
	in.Status.DeepCopyInto(&out.Status)
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new FleetFreeze.
func (in *FleetFreeze) DeepCopy() *FleetFreeze {
	if in == nil {
		return nil
	}
	out := new(FleetFreeze)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *FleetFreeze) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *FleetFreezeList) DeepCopyInto(out *FleetFreezeList) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ListMeta.DeepCopyInto(&out.ListMeta)
	if in.Items != nil {
		in, out := &in.Items, &out.Items
		*out = make([]FleetFreeze, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new FleetFreezeList.
func (in *FleetFreezeList) DeepCopy() *FleetFreezeList {
	if in == nil {
		return nil
	}
	out := new(FleetFreezeList)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *FleetFreezeList) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *FleetFreezeSpec) DeepCopyInto(out *FleetFreezeSpec) {
	*out = *in
	out.Scope = in.Scope
	if in.ExpiresAt != nil {
		in, out := &in.ExpiresAt, &out.ExpiresAt
		*out = (*in).DeepCopy()
	}
	if in.AllowUndo != nil {
		in, out := &in.AllowUndo, &out.AllowUndo
		*out = new(bool)
		**out = **in
	}
	if in.AllowClasses != nil {
		in, out := &in.AllowClasses, &out.AllowClasses
		*out = make([]FreezeClass, len(*in))
		copy(*out, *in)
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new FleetFreezeSpec.
func (in *FleetFreezeSpec) DeepCopy() *FleetFreezeSpec {
	if in == nil {
		return nil
	}
	out := new(FleetFreezeSpec)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *FleetFreezeStatus) DeepCopyInto(out *FleetFreezeStatus) {
	*out = *in
	if in.ActiveSince != nil {
		in, out := &in.ActiveSince, &out.ActiveSince
		*out = (*in).DeepCopy()
	}
	if in.Conditions != nil {
		in, out := &in.Conditions, &out.Conditions
		*out = make([]metav1.Condition, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new FleetFreezeStatus.
func (in *FleetFreezeStatus) DeepCopy() *FleetFreezeStatus {
	if in == nil {
		return nil
	}
	out := new(FleetFreezeStatus)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *FreezeScope) DeepCopyInto(out *FreezeScope) {
	*out = *in
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new FreezeScope.
func (in *FreezeScope) DeepCopy() *FreezeScope {
	if in == nil {
		return nil
	}
	out := new(FreezeScope)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *GitHubSpec) DeepCopyInto(out *GitHubSpec) {
	*out = *in
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new GitHubSpec.
func (in *GitHubSpec) DeepCopy() *GitHubSpec {
	if in == nil {
		return nil
	}
	out := new(GitHubSpec)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *GoogleChatNotify) DeepCopyInto(out *GoogleChatNotify) {
	*out = *in
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new GoogleChatNotify.
func (in *GoogleChatNotify) DeepCopy() *GoogleChatNotify {
	if in == nil {
		return nil
	}
	out := new(GoogleChatNotify)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *GoogleChatSpec) DeepCopyInto(out *GoogleChatSpec) {
	*out = *in
	if in.Enabled != nil {
		in, out := &in.Enabled, &out.Enabled
		*out = new(bool)
		**out = **in
	}
	if in.AllowedUsers != nil {
		in, out := &in.AllowedUsers, &out.AllowedUsers
		*out = make([]string, len(*in))
		copy(*out, *in)
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new GoogleChatSpec.
func (in *GoogleChatSpec) DeepCopy() *GoogleChatSpec {
	if in == nil {
		return nil
	}
	out := new(GoogleChatSpec)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *HarnessSpec) DeepCopyInto(out *HarnessSpec) {
	*out = *in
	if in.Hermes != nil {
		in, out := &in.Hermes, &out.Hermes
		*out = new(HermesSpec)
		(*in).DeepCopyInto(*out)
	}
	if in.Memory != nil {
		in, out := &in.Memory, &out.Memory
		*out = new(MemorySpec)
		(*in).DeepCopyInto(*out)
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new HarnessSpec.
func (in *HarnessSpec) DeepCopy() *HarnessSpec {
	if in == nil {
		return nil
	}
	out := new(HarnessSpec)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *HermesSpec) DeepCopyInto(out *HermesSpec) {
	*out = *in
	if in.DashboardEnabled != nil {
		in, out := &in.DashboardEnabled, &out.DashboardEnabled
		*out = new(bool)
		**out = **in
	}
	if in.PluginsDebug != nil {
		in, out := &in.PluginsDebug, &out.PluginsDebug
		*out = new(bool)
		**out = **in
	}
	if in.ApiServerSecretRef != nil {
		in, out := &in.ApiServerSecretRef, &out.ApiServerSecretRef
		*out = new(v1.SecretKeySelector)
		(*in).DeepCopyInto(*out)
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new HermesSpec.
func (in *HermesSpec) DeepCopy() *HermesSpec {
	if in == nil {
		return nil
	}
	out := new(HermesSpec)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *IACSpec) DeepCopyInto(out *IACSpec) {
	*out = *in
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new IACSpec.
func (in *IACSpec) DeepCopy() *IACSpec {
	if in == nil {
		return nil
	}
	out := new(IACSpec)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *InitiativeBudgetSpec) DeepCopyInto(out *InitiativeBudgetSpec) {
	*out = *in
	if in.SelfInitiated != nil {
		in, out := &in.SelfInitiated, &out.SelfInitiated
		*out = new(BudgetClassSpec)
		(*in).DeepCopyInto(*out)
	}
	if in.HumanRequested != nil {
		in, out := &in.HumanRequested, &out.HumanRequested
		*out = new(BudgetClassSpec)
		(*in).DeepCopyInto(*out)
	}
	if in.MaxObjectsPerAction != nil {
		in, out := &in.MaxObjectsPerAction, &out.MaxObjectsPerAction
		*out = new(int32)
		**out = **in
	}
	if in.FlapWindow != nil {
		in, out := &in.FlapWindow, &out.FlapWindow
		*out = new(metav1.Duration)
		**out = **in
	}
	if in.FlapThreshold != nil {
		in, out := &in.FlapThreshold, &out.FlapThreshold
		*out = new(int32)
		**out = **in
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new InitiativeBudgetSpec.
func (in *InitiativeBudgetSpec) DeepCopy() *InitiativeBudgetSpec {
	if in == nil {
		return nil
	}
	out := new(InitiativeBudgetSpec)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *IntegrationSpec) DeepCopyInto(out *IntegrationSpec) {
	*out = *in
	if in.GitHub != nil {
		in, out := &in.GitHub, &out.GitHub
		*out = new(GitHubSpec)
		**out = **in
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new IntegrationSpec.
func (in *IntegrationSpec) DeepCopy() *IntegrationSpec {
	if in == nil {
		return nil
	}
	out := new(IntegrationSpec)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *KindRefSpec) DeepCopyInto(out *KindRefSpec) {
	*out = *in
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new KindRefSpec.
func (in *KindRefSpec) DeepCopy() *KindRefSpec {
	if in == nil {
		return nil
	}
	out := new(KindRefSpec)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *MemorySpec) DeepCopyInto(out *MemorySpec) {
	*out = *in
	if in.MemoryEnabled != nil {
		in, out := &in.MemoryEnabled, &out.MemoryEnabled
		*out = new(bool)
		**out = **in
	}
	if in.UserProfileEnabled != nil {
		in, out := &in.UserProfileEnabled, &out.UserProfileEnabled
		*out = new(bool)
		**out = **in
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new MemorySpec.
func (in *MemorySpec) DeepCopy() *MemorySpec {
	if in == nil {
		return nil
	}
	out := new(MemorySpec)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *ObjectStoreRef) DeepCopyInto(out *ObjectStoreRef) {
	*out = *in
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new ObjectStoreRef.
func (in *ObjectStoreRef) DeepCopy() *ObjectStoreRef {
	if in == nil {
		return nil
	}
	out := new(ObjectStoreRef)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *OperationsSpec) DeepCopyInto(out *OperationsSpec) {
	*out = *in
	if in.Paused != nil {
		in, out := &in.Paused, &out.Paused
		*out = new(bool)
		**out = **in
	}
	if in.DryRunOnly != nil {
		in, out := &in.DryRunOnly, &out.DryRunOnly
		*out = new(bool)
		**out = **in
	}
	if in.ApprovalRosterRef != nil {
		in, out := &in.ApprovalRosterRef, &out.ApprovalRosterRef
		*out = new(RosterRef)
		**out = **in
	}
	if in.ChangePolicyRefs != nil {
		in, out := &in.ChangePolicyRefs, &out.ChangePolicyRefs
		*out = make([]PolicyRef, len(*in))
		copy(*out, *in)
	}
	if in.InitiativeBudget != nil {
		in, out := &in.InitiativeBudget, &out.InitiativeBudget
		*out = new(InitiativeBudgetSpec)
		(*in).DeepCopyInto(*out)
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new OperationsSpec.
func (in *OperationsSpec) DeepCopy() *OperationsSpec {
	if in == nil {
		return nil
	}
	out := new(OperationsSpec)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *OperationsStatus) DeepCopyInto(out *OperationsStatus) {
	*out = *in
	if in.PausedSince != nil {
		in, out := &in.PausedSince, &out.PausedSince
		*out = (*in).DeepCopy()
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new OperationsStatus.
func (in *OperationsStatus) DeepCopy() *OperationsStatus {
	if in == nil {
		return nil
	}
	out := new(OperationsStatus)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *ParentRefSpec) DeepCopyInto(out *ParentRefSpec) {
	*out = *in
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new ParentRefSpec.
func (in *ParentRefSpec) DeepCopy() *ParentRefSpec {
	if in == nil {
		return nil
	}
	out := new(ParentRefSpec)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *PolicyRef) DeepCopyInto(out *PolicyRef) {
	*out = *in
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new PolicyRef.
func (in *PolicyRef) DeepCopy() *PolicyRef {
	if in == nil {
		return nil
	}
	out := new(PolicyRef)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *PreStateSnapshot) DeepCopyInto(out *PreStateSnapshot) {
	*out = *in
	in.CapturedAt.DeepCopyInto(&out.CapturedAt)
	if in.Object != nil {
		in, out := &in.Object, &out.Object
		*out = new(runtime.RawExtension)
		(*in).DeepCopyInto(*out)
	}
	if in.ObjectRef != nil {
		in, out := &in.ObjectRef, &out.ObjectRef
		*out = new(ObjectStoreRef)
		**out = **in
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new PreStateSnapshot.
func (in *PreStateSnapshot) DeepCopy() *PreStateSnapshot {
	if in == nil {
		return nil
	}
	out := new(PreStateSnapshot)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *RecoveryTransition) DeepCopyInto(out *RecoveryTransition) {
	*out = *in
	in.At.DeepCopyInto(&out.At)
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new RecoveryTransition.
func (in *RecoveryTransition) DeepCopy() *RecoveryTransition {
	if in == nil {
		return nil
	}
	out := new(RecoveryTransition)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *RetentionSpec) DeepCopyInto(out *RetentionSpec) {
	*out = *in
	in.ExpiresAt.DeepCopyInto(&out.ExpiresAt)
	in.UndoWindowExpiresAt.DeepCopyInto(&out.UndoWindowExpiresAt)
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new RetentionSpec.
func (in *RetentionSpec) DeepCopy() *RetentionSpec {
	if in == nil {
		return nil
	}
	out := new(RetentionSpec)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *RosterRef) DeepCopyInto(out *RosterRef) {
	*out = *in
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new RosterRef.
func (in *RosterRef) DeepCopy() *RosterRef {
	if in == nil {
		return nil
	}
	out := new(RosterRef)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *ScopeSpec) DeepCopyInto(out *ScopeSpec) {
	*out = *in
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new ScopeSpec.
func (in *ScopeSpec) DeepCopy() *ScopeSpec {
	if in == nil {
		return nil
	}
	out := new(ScopeSpec)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *SecuritySpec) DeepCopyInto(out *SecuritySpec) {
	*out = *in
	if in.ServiceAccountAnnotations != nil {
		in, out := &in.ServiceAccountAnnotations, &out.ServiceAccountAnnotations
		*out = make(map[string]string, len(*in))
		for key, val := range *in {
			(*out)[key] = val
		}
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new SecuritySpec.
func (in *SecuritySpec) DeepCopy() *SecuritySpec {
	if in == nil {
		return nil
	}
	out := new(SecuritySpec)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *ServiceStatus) DeepCopyInto(out *ServiceStatus) {
	*out = *in
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new ServiceStatus.
func (in *ServiceStatus) DeepCopy() *ServiceStatus {
	if in == nil {
		return nil
	}
	out := new(ServiceStatus)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *SlackNotify) DeepCopyInto(out *SlackNotify) {
	*out = *in
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new SlackNotify.
func (in *SlackNotify) DeepCopy() *SlackNotify {
	if in == nil {
		return nil
	}
	out := new(SlackNotify)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *SlackSpec) DeepCopyInto(out *SlackSpec) {
	*out = *in
	if in.Enabled != nil {
		in, out := &in.Enabled, &out.Enabled
		*out = new(bool)
		**out = **in
	}
	if in.BotTokenSecretRef != nil {
		in, out := &in.BotTokenSecretRef, &out.BotTokenSecretRef
		*out = new(v1.SecretKeySelector)
		(*in).DeepCopyInto(*out)
	}
	if in.AppTokenSecretRef != nil {
		in, out := &in.AppTokenSecretRef, &out.AppTokenSecretRef
		*out = new(v1.SecretKeySelector)
		(*in).DeepCopyInto(*out)
	}
	if in.AllowedUsers != nil {
		in, out := &in.AllowedUsers, &out.AllowedUsers
		*out = make([]string, len(*in))
		copy(*out, *in)
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new SlackSpec.
func (in *SlackSpec) DeepCopy() *SlackSpec {
	if in == nil {
		return nil
	}
	out := new(SlackSpec)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *StorageStatus) DeepCopyInto(out *StorageStatus) {
	*out = *in
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new StorageStatus.
func (in *StorageStatus) DeepCopy() *StorageStatus {
	if in == nil {
		return nil
	}
	out := new(StorageStatus)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *TargetRef) DeepCopyInto(out *TargetRef) {
	*out = *in
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new TargetRef.
func (in *TargetRef) DeepCopy() *TargetRef {
	if in == nil {
		return nil
	}
	out := new(TargetRef)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *UndoPlan) DeepCopyInto(out *UndoPlan) {
	*out = *in
	in.GeneratedAt.DeepCopyInto(&out.GeneratedAt)
	if in.Steps != nil {
		in, out := &in.Steps, &out.Steps
		*out = make([]UndoStep, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
	if in.Caveats != nil {
		in, out := &in.Caveats, &out.Caveats
		*out = make([]string, len(*in))
		copy(*out, *in)
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new UndoPlan.
func (in *UndoPlan) DeepCopy() *UndoPlan {
	if in == nil {
		return nil
	}
	out := new(UndoPlan)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *UndoPrecondition) DeepCopyInto(out *UndoPrecondition) {
	*out = *in
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new UndoPrecondition.
func (in *UndoPrecondition) DeepCopy() *UndoPrecondition {
	if in == nil {
		return nil
	}
	out := new(UndoPrecondition)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *UndoRequest) DeepCopyInto(out *UndoRequest) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ObjectMeta.DeepCopyInto(&out.ObjectMeta)
	in.Spec.DeepCopyInto(&out.Spec)
	in.Status.DeepCopyInto(&out.Status)
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new UndoRequest.
func (in *UndoRequest) DeepCopy() *UndoRequest {
	if in == nil {
		return nil
	}
	out := new(UndoRequest)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *UndoRequest) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *UndoRequestList) DeepCopyInto(out *UndoRequestList) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ListMeta.DeepCopyInto(&out.ListMeta)
	if in.Items != nil {
		in, out := &in.Items, &out.Items
		*out = make([]UndoRequest, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new UndoRequestList.
func (in *UndoRequestList) DeepCopy() *UndoRequestList {
	if in == nil {
		return nil
	}
	out := new(UndoRequestList)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *UndoRequestList) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *UndoRequestSpec) DeepCopyInto(out *UndoRequestSpec) {
	*out = *in
	out.ActionRef = in.ActionRef
	if in.MarkContested != nil {
		in, out := &in.MarkContested, &out.MarkContested
		*out = new(bool)
		**out = **in
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new UndoRequestSpec.
func (in *UndoRequestSpec) DeepCopy() *UndoRequestSpec {
	if in == nil {
		return nil
	}
	out := new(UndoRequestSpec)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *UndoRequestStatus) DeepCopyInto(out *UndoRequestStatus) {
	*out = *in
	if in.CompletionTime != nil {
		in, out := &in.CompletionTime, &out.CompletionTime
		*out = (*in).DeepCopy()
	}
	if in.Conditions != nil {
		in, out := &in.Conditions, &out.Conditions
		*out = make([]metav1.Condition, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new UndoRequestStatus.
func (in *UndoRequestStatus) DeepCopy() *UndoRequestStatus {
	if in == nil {
		return nil
	}
	out := new(UndoRequestStatus)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *UndoStep) DeepCopyInto(out *UndoStep) {
	*out = *in
	out.Target = in.Target
	if in.Object != nil {
		in, out := &in.Object, &out.Object
		*out = new(runtime.RawExtension)
		(*in).DeepCopyInto(*out)
	}
	if in.ObjectRef != nil {
		in, out := &in.ObjectRef, &out.ObjectRef
		*out = new(ObjectStoreRef)
		**out = **in
	}
	if in.Preconditions != nil {
		in, out := &in.Preconditions, &out.Preconditions
		*out = new(UndoPrecondition)
		**out = **in
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new UndoStep.
func (in *UndoStep) DeepCopy() *UndoStep {
	if in == nil {
		return nil
	}
	out := new(UndoStep)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *VerificationCheck) DeepCopyInto(out *VerificationCheck) {
	*out = *in
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new VerificationCheck.
func (in *VerificationCheck) DeepCopy() *VerificationCheck {
	if in == nil {
		return nil
	}
	out := new(VerificationCheck)
	in.DeepCopyInto(out)
	return out
}
